### ISSUE TITLE
Not working for emojis

### ISSUE THREAD

**Issue by arefeenm** [oozcitak/xmlbuilder-js#100]
If I try to stringify a text that contains an emoji, the error 'Invalid Character' gets thrown. Tried using both `{version: '1.0', encoding: 'UTF-8'}` and 32 encoding, doesn't work. What am I missing?

**Comment by oozcitak** [comment]
Did you see Issue #98?

**Comment by arefeenm** [comment]
Awesome, thanks. Sorry did not see the closed issues.
