### ISSUE TITLE
Same keys contained within an object don't get built

### ISSUE THREAD

**Issue by alexzkazu** [oozcitak/xmlbuilder-js#104]
If I did the following:

```
var xml = builder.create({
   response :{
      test: {
           hello: 'hello',
           hello: 'bye'
      }
   }
}).end({pretty:true});
```

The console output comes out as: 

```
<?xml version="1.0"?>
<response>
  <test>
    <hello>bye</hello>
  </test>
</response>
```

Is there a way to make both of the keys show up? Thanks!

**Comment by addaleax** [comment]
```js
var xml = builder.create({
   response: {
      test: {
         hello: ['hello', 'bye']
      }
   }
}).end({pretty:true});
```
results in
```xml
<?xml version="1.0"?>
<response>
  <test>
    <hello>hello</hello>
    <hello>bye</hello>
  </test>
</response>
```

**Comment by alexzkazu** [comment]
Ah great! If I wanted to add attributes to both of the hellos, is there a way to do that as well?

**Comment by addaleax** [comment]
There are some pretty good examples at [the wiki](https://github.com/oozcitak/xmlbuilder-js/wiki/Conversion-From-Object) – You may want something like the
```js
phone: [
  { '#text': "555-1234", '@type': 'home' }, 
  { '#text': "555-1235", '@type': 'mobile' }
],
```
entries, I guess. :)

**Comment by alexzkazu** [comment]
Ahh, I totally overlooked the other pages on the wiki! Sorry about that, and thanks!
