### ISSUE TITLE
What changed with the 4.0 release?

### ISSUE THREAD

**Issue by PanMan** [oozcitak/xmlbuilder-js#106]
Hi.
I'm currently running a nodejs project which uses xmlbuilder 3.1.0. Maybe I'm overlooking things, but where can I find what changed with the 4.0 release? Any breaking changes I should check for?

**Comment by oozcitak** [comment]
I don't keep a changelog but the major change was the removal of the `#list` decorator and how arrays are handled when converting from JS objects. See: https://github.com/oozcitak/xmlbuilder-js/wiki/Conversion-From-Object#arrays. For example:

```js
root.ele({
  number: [ 
    "one", 
    "two"
  ]
});
// v3 result
<number>
  <one/>
  <two/>
</number>
// v4 result
<number>one</number>
<number>two</number>
```

This is the only potentially breaking change between v3 and v4. Other than that there are a few new features and bug fixes, but those should be all backwards compatible.

Here is the list of all changes: https://github.com/oozcitak/xmlbuilder-js/compare/v3.1.0...v4.2.1

**Comment by oozcitak** [comment]
We now have a change log: https://github.com/oozcitak/xmlbuilder-js/blob/master/CHANGELOG.md
