### ISSUE TITLE
HTML cannot handle self-closing tags

### ISSUE THREAD

**Issue by hennes-maertins** [oozcitak/xmlbuilder-js#109]
I am using xmlbuilder-js to generate html code. In my special case I want to generate an &lt;iframe&gt; tag to embed another html page. <s>I cannot do this by generating xhtml because xhtml doesn't support iframes.</s>(I am wrong. See comment below.)

Unfortunately html does not handle self-closing tags as needed. The problem is described well here:
* https://stackoverflow.com/questions/3558119/are-self-closing-tags-valid-in-html5#3558200
* https://stackoverflow.com/questions/27545757/why-is-a-self-closing-iframe-tag-preventing-further-dom-elements-to-be-displayed#27545784

A way to generate empty tags (&lt;iframe&gt;&lt;/iframe&gt;) instead of self-closing tags (&lt;iframe/&gt;) would save the day. As described in #65 self-closing tags are needed too, so the behaviour has to be configurable.

You might say that using a tool to build xml is not a good choice to build html, but I like xmlbuilder-js and I would be glad if I could use it for my use case.

**Comment by hennes-maertins** [comment]
Update:
I was wrong about the usage of iframes in xhtml. I was able to generate an xhtml file with an iframe and my firefox was able to render it. So my problem has been solved.

Please decide if an option to create empty tags might still be useful. I guess such an option would help you to generate valid html5 which is more modern than xhtml. ;-)

**Comment by oozcitak** [comment]
Support for empty tags was added recently. See #103.

**Comment by hennes-maertins** [comment]
Thank you very much! I overlooked that issue.
