### ISSUE TITLE
Root attributes

### ISSUE THREAD

**Issue by iagomr** [oozcitak/xmlbuilder-js#110]
Hey,

Sorry but I couldn't find a way to add attributes on the root. Is there a way to do so?

Cheers

**Comment by iagomr** [comment]
sorry didn't look through the solved issues, but would be cool to have it in the documentation!

**Comment by oozcitak** [comment]
Thank you. I just added some explanation to the wiki: https://github.com/oozcitak/xmlbuilder-js/wiki
