### ISSUE TITLE
Object.assign() on not-so-old nwjs

### ISSUE THREAD

**Issue by vankasteelj** [oozcitak/xmlbuilder-js#111]
Hi,

Your new versions (I use 4.x normally) aren't compatible with nwjs 0.12.3, because of the `Object.assign()` in "create" method. 

May I suggest you to use a polyfill (plain or as a dep) to allow support of a little older platforms? 

I'll PR 2 different possibilities to solve the matter, if you like one of them and are OK with supporting a greater range of platforms, please merge it :) 

Thanks!

**Comment by oozcitak** [comment]
This should do it: 9972cffeb09a119cab426d906c48832d599ad2a2

Thank you
