### ISSUE TITLE
possible memory leak in XMLStringWriter.js

### ISSUE THREAD

**Issue by jcollum** [oozcitak/xmlbuilder-js#115]
I've seen my process die for the error `CALL_AND_RETRY_LAST Allocation failed - process out of memory` several times in the past week. `XMLStringWriter.js` is usually what I see in the dump logs:  

```
    2: element [/opt/asdf/ljlkj/node_modules/xmlbuilder/lib/XMLStringWriter.js:~138] [pc=0x361fa2f75548] (this=0x1e7f1ba2d851 <an XMLStringWriter with map 0x1cfdad2ddfa9>,node=0xecb32921051 <an XMLElement with map 0x1cfdad2dcc11>,level=8)
    3: /* anonymous */ [/opt/asdf/ljlkj/node_modules/xmlbuilder/lib/XMLStringWriter.js:174] [pc=0x361fa2f745e5] (this=0x...
```

My process has 4GB available memory, it's started with `--max-old-space-size=4096`. I am building some fairly large xml docs but 4GB seems like a lot of space. The memory usage reported is typically under 100MB according to PM2. 

I have a memory leak watcher setup: 

```
if process.env.NODE_ENV is 'development'
  # memory leak detection
  memwatch = require('memwatch-next')
  heapdump = require('heapdump')

  console.log 'setting up memory watch'
  memwatch.on 'leak', (info) ->
    console.error('Memory leak detected: ', info)
    file = '/tmp/serd-insp-' + process.pid + '-' + Date.now() + '.heapsnapshot';

    heapdump.writeSnapshot file, (err) ->
      if (err?) then console.error(err)
      else console.error('Wrote snapshot: ' + file)
```

The watcher gets set up but I never see the 'leak' event fire. 

Suggestions? I've seen XMLStringWriter.js many times in the error dump when this happens, it seems like the most likely culprit.

**Comment by oozcitak** [comment]
I did some tests also with `memwatch` but couldn't get any memory leaks. I'll continue to investigate this. Is there any more info can share?

In the meantime you can also take a look at the callback API: https://github.com/oozcitak/xmlbuilder-js/wiki#begin-with-callback. This was added a few days ago. It should use a lot less memory if you do not need to traverse or modify the XML tree.

**Comment by jcollum** [comment]
Thanks Ozgur. I don't have any more info to give you. If the callback API fixes it I will let you know. It'll be a few days before I know.
