### ISSUE TITLE
Prettify output stream

### ISSUE THREAD

**Issue by pedro93** [oozcitak/xmlbuilder-js#116]
Hi!

I was taking a look at this lib and trying to stream a dynamically generated XML to process.stdout. I wanted to prettify the output with newlines and tabs.

I have the following code but it does not seem to work
```js
"use strict";

const xmlbuilder = require('xmlbuilder');

function Delta(dom1Nodes, dom2Nodes){
    this.dom1Nodes = dom1Nodes;
    this.dom2Nodes = dom2Nodes;
    // this.writer = builder.streamWriter(process.stdout); // pass a writable stream
    this.xml = xmlbuilder.begin(function(chunk) { process.stdout.write(chunk); });

}

Delta.prototype.output = function () {
    this.xml.dec('1.0', 'UTF-8', false)
    .ele('root')
    .ele('xmlbuilder').up()
    .ele('repo', {'type': 'git'}, 'git://github.com/oozcitak/xmlbuilder-js.git')
    .end({pretty: true});
};

var delta = new Delta([],[]); //parameters are irrelevant to showcase the example
delta.output();
module.exports = Delta;
```
The output I get is:
```bash
<?xml version="1.0" encoding="UTF-8" standalone="no"?><root><xmlbuilder/><repo type="git">git://github.com/oozcitak/xmlbuilder-js.git</repo></root>
```
All in a single line. Shouldn't 
```js 
.end({pretty: true}); 
``` 
correctly indent it? If not what am I doing wrong or is this unachievable natively with the lib?

Thanks for reading :)

**Comment by oozcitak** [comment]
`begin` was added a few days ago, so the documentation is a bit lacking. When you pass a callback function to `begin` XML nodes are written as they are processed. This means that any option you pass to `end` will be ignored since the nodes will already be written. The workaround is to pass formatting options to `begin`'s optional argument with the `writer` key, e.g.

```js
this.xml = xmlbuilder.begin(
  { writer: { pretty: true } },
  function(chunk) { process.stdout.write(chunk); }
);
```

**Comment by pedro93** [comment]
This solved my problem thank you
