### ISSUE TITLE
Passing 0 as element content collapses the element.

### ISSUE THREAD

**Issue by pixelfreak** [oozcitak/xmlbuilder-js#117]
When passing the integer `0` the content to an element. It used to be this:

`<element>0</element>`

Now it's:

`<element />`

Is this intentional? Why?

**Comment by oozcitak** [comment]
No, this is a bug. I'm looking into it.

**Comment by oozcitak** [comment]
Fixed with 579f361e81b4d28ca402016dcf28357d13e1601f

**Comment by pixelfreak** [comment]
Thanks, is this going to be part of 8.2.2?

**Comment by oozcitak** [comment]
The fix is in the current 8.2.1 release.

**Comment by oozcitak** [comment]
Also fixed this bug in callback mode (i.e. `begin` with a callback function) This fix is in 8.2.2.
