### ISSUE TITLE
Support for namespaces

### ISSUE THREAD

**Issue by oskar-bitaddict** [oozcitak/xmlbuilder-js#118]
For what I can see there is no support for using namespaces? Maybe that could be a feature worth implementing?

**Comment by alexchiri** [comment]
Would be nice to have support for namespaces. In the meantime should work to use the basic att function and provide a `xmlns:namespace` name for the attribute.

**Comment by jpepper07** [comment]
I have had no issues creating the nodes a name like 'xsl:template'. Nothing stop this from working. I generate dynamic XSLTs in this manner.

**Comment by oozcitak** [comment]
XML namespaces are supported in newly released [`xmlbuilder2`](https://github.com/oozcitak/xmlbuilder2/wiki/Namespaces). Please upgrade if possible.
