### ISSUE TITLE
Add html as text data of node

### ISSUE THREAD

**Issue by pedro93** [oozcitak/xmlbuilder-js#119]
I am attempting to insert a textual representation of html as the text of a node, however the '<', '/' and '>' characters are getting converted. Is there a solution to this?

JS code 
```js
xmlNode.ele('element',bodyInnerHtml);
```
Result:
```xml
<xy:d par="11" pos="1" xm="10">
    <element>
                    &lt;div class="front_clip"&gt;
                        &lt;div class="ring_clip"&gt; &lt;/div&gt;
                    &lt;/div&gt;
                </element>
  </xy:d>
```

**Comment by oozcitak** [comment]
Try using [`raw`](https://github.com/oozcitak/xmlbuilder-js/wiki#raw-text-nodes):

```js
xmlNode.ele('element').raw(bodyInnerHtml);
```

**Comment by pedro93** [comment]
Thank you that worked :)

**Comment by pedro93** [comment]
Is it possible to format the raw content by attempting to treat it as xml? In my case I have html so it should be in theory possible:
Have this:
```xml
<xy:d par="9" pos="1" xm="8"><div class="front_clip"><div class="ring_clip"></div></div></xy:d>
```
And I intended this:
```xml
<xy:d par="9" pos="1" xm="8">
   <div class="front_clip">
      <div class="ring_clip">
      </div>
   </div>
</xy:d>
```

**Comment by oozcitak** [comment]
If I understood your question correctly; you want to parse a string containing some html as xml then feed it to `xmlbuilder`. If this is the case `xmlbuilder` does not support parsing xml (or html in your case).
