### ISSUE TITLE
Get node elements by namespace

### ISSUE THREAD

**Issue by pedro93** [oozcitak/xmlbuilder-js#122]
Is it possible to to get all elements of a particular tag name and update their content dynamically before calling the end() function.

For example, if we want to change a node's attribute or add children node to it after the node has been created. 
If we want to apply this change to all nodes of a particular tag name, how can we do it? Do we have to manually keep a reference to all nodes of that type or does the lib supply a method or call that provides us with this functionality?

``` js
var listOfNodes = xmlbuilder.get("client") //returns a list of all nodes with tagname clients.
listOfNodes.forEach(function(node){
       node.att("city","NY");
});
```

Thanks.

**Comment by oozcitak** [comment]
I have plans to add XPath support in the future, but currently this is not possible out of the box.

**Comment by jpepper07** [comment]
I was trying to find support for this. Currently my only work around is to make sure I understand where I am at in my current node structure. If I reference the xml object elsewhere then I am out of luck as I wont be able to target the proper node.

**Comment by oozcitak** [comment]
Just added support for external XPath libraries with 5d592d03d14dab25a29aae779b4287318a4d244b. For example using [`xpath`](https://github.com/goto100/xpath):
``` js
const builder = require('xmlbuilder');
const xpath = require('xpath');

let doc = xml('clients')
  .ele('client').att('city', 'CA').up()
  .ele('client').up()
  .doc()

let nodes = xpath.select('//client', doc);

nodes.forEach(function(node) {
  node.att("city", "NY");
});

// the xml document becomes:
// <?xml version="1.0"?>
// <clients>
//   <client city="NY"/>
//   <client city="NY"/>
// </clients>
```

**Comment by ayk-caglayan** [comment]
Is there a way to address a node and change its values on browser (without using node.j, just with default xpath support)?
