### ISSUE TITLE
Dynamically add children nodes to js Object to be converted

### ISSUE THREAD

**Issue by pedro93** [oozcitak/xmlbuilder-js#124]
Hi! 
I can't seem to find a way to do this.
I have a js obj to which I want to dynamically add children nodes, but they are not all of the same, how can I go about doing this?

Example
```js
var ops = [];
populateOps(ops); //adds elements to array (each is a json)
var node = {};
node[@pos] = 0;
node[@id] = 1;
node[#raw] = "some text here";

for(let i=0; i<op.length; i++){
 if(op.type == OP.insert){
  var child = {};
  child[tagname?] = "xy:insert";
  child[@prop1] = op.metaData;
  child[#raw] = op.data;
   node.children.push()
 } 
.... // there are more cases to add, each is a different tag
}
```

I can't declare the child name what I want because it may contain ilegal naming tokens such as ":"

**Comment by oozcitak** [comment]
I don't understand your question. What do you want to achieve (with `xmlbuilder`)? What have you tried? What didn't work?

**Comment by pedro93** [comment]
Hi, sorry I did not explain myself well, I have in the meantime figured out how to do this by creating the xmlbuilder element object based on an object. 
My issue was how to set the tagname for child elements because I could not find a decorator for it.

This was my solution.
```js
if(op[i].type == OP.insert)
   node.children.push(root.ele("xy:ti",{"pos": op[i].pos},op[i].content));
```
This issue can now be closed.
