### ISSUE TITLE
XMLStringifier.elEscape

### ISSUE THREAD

**Issue by konstantinov90** [oozcitak/xmlbuilder-js#126]
Dear Contributors and Oozcitak specifically! 

Thanks a lot for your package! I didn't know where to ask, so...

Why did you omit `.replace(/"/g, '&quot;')` in `elEscape` function in `XMLStringifier` module? Is it deliberate?

**Comment by oozcitak** [comment]
It is deliberate. See: https://www.w3.org/TR/2000/WD-xml-c14n-20000119.html#charescaping

It is easy to override though:

``` js
var root = xmlbuilder.create('root', {
  stringify: {
    elEscape: function(str) {
      return str.replace(/&/g, '&amp;')
                .replace(/</g, '&lt;')
                .replace(/>/g, '&gt;')
                .replace(/"/g, '&quot;');
    }
  }
});
```
