### ISSUE TITLE
String encoding failing for xml node attribute while doing builder.create

### ISSUE THREAD

**Issue by naveenwy** [oozcitak/xmlbuilder-js#127]
```
var obj = { 'Constant': { '@Value': '<Hello>' } }
xmlbuilder.create(obj).toString()
<Constant Value="&lt;Hello>"/>
```
It should've returned
`<Constant Value="&lt;Hello&gt;"/>`

**Comment by konstantinov90** [comment]
It's the same issue as [https://github.com/oozcitak/xmlbuilder-js/issues/126](url), but related to function `XMLStringifier.prototype.attEscape`.

You may add `.replace(/</g, '&lt;')` into that function, that should do it.

**Comment by oozcitak** [comment]
See: https://github.com/oozcitak/xmlbuilder-js/issues/126#issuecomment-252391245
