### ISSUE TITLE
Doctype root name

### ISSUE THREAD

**Issue by Grigory90** [oozcitak/xmlbuilder-js#128]
Hello.
How to install doctype root name? See example:

**Input:**
``` javascript
	var result = xmlBuilder.create('tag', {
		'pubID': 'aaa',
		'sysID': 'bbb'
	});
```
**Output:**
``` xml
<!DOCTYPE tag PUBLIC "aaa" "bbb">
<tag>
  ...
</tag>
```
**Necessary**
``` xml
<!DOCTYPE customName PUBLIC "aaa" "bbb">
<tag>
  ...
</tag>
```
Thank you in advance.

**Comment by oozcitak** [comment]
This would be invalid XML. If you must do this anyway; see `docType` in https://github.com/oozcitak/xmlbuilder-js/wiki#xml-writers and also its implementation in https://github.com/oozcitak/xmlbuilder-js/blob/master/src/XMLStringWriter.coffee#L67.
