### ISSUE TITLE
adding xsd validation

### ISSUE THREAD

**Issue by bdunn-sovos** [oozcitak/xmlbuilder-js#130]
I'm not seeing any way to validate xml generated using a xsd. this would really come in handy.

**Comment by machineghost** [comment]
Agreed.  Even just a way to easily plug-in another existing validation library would be handy.

**Comment by edtguy** [comment]
I'm using libxml-xsd. It was a bit of a challenge to install, but it is working well for me.

**Comment by oozcitak** [comment]
I have just added an example to the [`xmlbuilder2` wiki](https://github.com/oozcitak/xmlbuilder2/wiki/Using-with-External-Libraries#libxmljs). It should also be usable with `xmlbuilder` with a few changes.
