### ISSUE TITLE
Creation of element validation

### ISSUE THREAD

**Issue by FraGoTe** [oozcitak/xmlbuilder-js#132]
is there a way to do something like this? :

```
if (x === true) {
       subInfo
       .ele('yo')
       .up()
       .end();
} else {
       subInfo = '';
}


document
    .ele('ext:UBLExtensions')
      .ele('ext:UBLExtension')
        subInfo
      .up()
    .up()
.end();


```

**Comment by oozcitak** [comment]
You could build an XML fragment and import it using [`importDocument`](https://github.com/oozcitak/xmlbuilder-js/blob/ab5987b12bc06e4da8c37cd7fec8f93085d96d28/src/XMLNode.coffee#L419).
