### ISSUE TITLE
allowEmpty fails 

### ISSUE THREAD

**Issue by taschana** [oozcitak/xmlbuilder-js#133]
I've got a complex routine to build xml (even generating some namespace for myself), all is well, except for the allowEmpty part.
Generating the string like this:
` xmlObject.end({ pretty: true, newLine: "\n", allowEmpty: true })`
produces an output like that:
`<sch:comsumptionTier xsi:nil="true"/>`

I am not sure if an object is not considered "empty" anymore, when it contains an attribute, but this shouldn't prevent the algorithm from producing a closing tag.

Please help me find and (hot)fix this. 
Thanks a lot for the otherwise great plugin and I am looking forward to new features!

Natascha

PS: if you want more code to debug this, just say so.

**Comment by oozcitak** [comment]
Please see: https://github.com/oozcitak/xmlbuilder-js/wiki#converting-to-string. You need to set `allowEmpty: false` if you want closing tags always.

**Comment by hatton** [comment]
I don't understand. Taschana seemed to be asking for NON-self-closing tags. @oozcitak your answer seems to just tell her how to get self-closing tags. 

I'm pointing this out because I, too, am setting ``allowEmpty: true`` and yet I, too, am getting ``<mytag/>``.

**Comment by oozcitak** [comment]
Can you submit a test case please?
