### ISSUE TITLE
Can't use same name for adjacent xml tags

### ISSUE THREAD

**Issue by sam-rez** [oozcitak/xmlbuilder-js#134]
`var xml = builder.create({
  channel: {
      name: {
          '#text' : "text"
      },
      profile_id: {
          '#text' : "text"
      },
      channel_params : {
          '@type' : 'array',
          channel_param : {
              name : {
                  '#text' : "text"
              },
              value : {
                  '#text' : "text"
              }
          },
          channel_param : {
              name : {
                  '#text' : "text"
              }
          }
      }
  }
}).end({ pretty: true});`

channel_param will only generate one tag. However if I change one of them to channel_param2, it will generate two different tags.

**Comment by oozcitak** [comment]
You have multiple entries with the same key in your JSON object. This would result in one being overridden by the other. You could enclose those entries in an [array](https://github.com/oozcitak/xmlbuilder-js/wiki/Conversion-From-Object#arrays).
