### ISSUE TITLE
how to declare doctype?

### ISSUE THREAD

**Issue by chovy** [oozcitak/xmlbuilder-js#136]
The example does not work for me:

```
const xml = builder.create('foo', {
    version: '1.0',
    encoding: 'UTF-8'
  })
```

I do not get: `<?xml version="1.0" encoding="UTF-8"?>` in the output. The docs say it will be the default with no options passed to `.create()` but that didn't work for me either.

Please respond, I see lots of issues asking this same question and please update docs if it no longer works.

I also tried this straight from docs: 

```
  return builder.create('root')
    .dec('1.0', 'UTF-8', true)
    .ele('node');
```

still no doctype.

**Comment by oozcitak** [comment]
Copy/pasted your sample:
``` js
const builder = require('./lib/index.js');

const xml = builder.create('foo', {
    version: '1.0',
    encoding: 'UTF-8'
  });

const xmlString = xml.end();

console.log(xmlString);
```
This is what the console shows:
``` xml
<?xml version="1.0" encoding="UTF-8"?><foo/>
```
You seem to be missing `end`.
