### ISSUE TITLE
How to concatenate two XML trees?

### ISSUE THREAD

**Issue by nschoe** [oozcitak/xmlbuilder-js#137]
Hi,
I'm not sure if this is a missing feature or if I am missing the point (probably the latter because what I'm trying to achieve is pretty straightforward and I can't see anybody else complaining :-)).

So basically, I have an object `obj`, which contains several other objects, say 2: `obj.sub1 = {...}` and `obj.sub2 = {...}`. Now, `sub1` and `sub2` contains some properties, etc, and a function `introspect()` which generates some introspection data, in XML.

`obj` also has a function `introspect()` which should call each of it's subobject's `introspect()` function, get the result, concatenate it and return. And this is where I'm stuck:

```Javascript
obj.introspect = function() {
    let xml1 = obj.sub1.introspect()
    let xml2 = obj.sub2.introspect()

   let finalXML = xmlbuilder.create ('root')
   finalXML.ele ('something')
   finalXML.ele ('something-else')

   // how can I append xml1 and xml2 at the end of finalXML?
}
```

To have more concrete example, I'm currently writing a DBus implementation, and I need to concatenate several introspection data.

So, `sub1` and `sub` generates their portion of xml, which looks like this (to generate this pretty output I have called `.end ({pretty: true})`, but in my code, I have not called `.env()` since I want them to return an xml tree, not a string:
```xml
<interface name="com.dbus.native.basic.service">
  <method name="Capitalize">
    <arg type="s" name="initial_string" direction="in"/>
    <arg type="s" name="capitalized_string" direction="out"/>
  </method>
  <method name="SayHello">
    <arg type="s" name="hello_sentence" direction="out"/>
  </method>
  <signal name="Rand">
    <arg type="i" name="random_number"/>
  </signal>
  <property name="Flag" type="b" access="readonly"/>
  <property name="StringProp" type="s" access="readwrite"/>
</interface>
```

I had the feeling that this could be achieved with the `begin()` function, but I don't understand how it is used, how to pass it arguments, etc.

Can you help?

Thanks.

**Comment by oozcitak** [comment]
You could do this with the undocumented but suported import function: [`importDocument`](https://github.com/oozcitak/xmlbuilder-js/blob/ab5987b12bc06e4da8c37cd7fec8f93085d96d28/src/XMLNode.coffee#L419).

**Comment by nschoe** [comment]
Thanks @oozcitak , any reason this is not documented?

Actually I have found a way out: `obj`'s `introspect()` function generates the xml root, and pass it to `sub1`'s `introspect()` function which created its nodes on the supplied root.
This way I only use valid, documented functions.

But I'd be interested to know why `importDocument` is not part of the API?

**Comment by oozcitak** [comment]
Laziness most probably. I'll get around to document it eventually.

**Comment by nschoe** [comment]
Okay cool.
Well I'm closing, then. I'll let my answer with passing the xml root as parameters: could be useful to others .

**Comment by oozcitak** [comment]
Thank you. I'll document the import function in a few days: #138
