### ISSUE TITLE
Error in XMLElement.js in Ionic2 App for using node-rest-client and xml2js

### ISSUE THREAD

**Issue by math10** [oozcitak/xmlbuilder-js#139]
XMLElement.js:4 Uncaught TypeError: Cannot read property 'prototype' of undefined

```
"dependencies": {
    "@angular/common": "^2.1.0",
    "@angular/compiler": "^2.1.0",
    "@angular/compiler-cli": "^2.1.0",
    "@angular/core": "^2.1.0",
    "@angular/forms": "^2.1.0",
    "@angular/http": "^2.1.0",
    "@angular/platform-browser": "^2.1.0",
    "@angular/platform-browser-dynamic": "^2.1.0",
    "@angular/platform-server": "^2.1.0",
    "@ionic/app-scripts": "0.0.30",
    "@ionic/storage": "^1.1.6",
    "@types/md5": "^2.1.31",
    "@types/xml2js": "0.0.28",
    "ionic-angular": "^2.0.0-rc.0",
    "ionic-native": "^2.2.2",
    "ionicons": "^3.0.0",
    "md5": "^2.2.1",
    "node-rest-client": "^2.0.1",
    "rxjs": "^5.0.0-beta.12",
    "typescript": "^2.0.3",
    "zone.js": "^0.6.25"
  }
```

ionic : 2.1.0
node : 6.7.8

Is there any way to solve this error?

**Comment by oozcitak** [comment]
I'll need more information. Please post some code.

**Comment by math10** [comment]
@oozcitak Could you please see this [app](https://github.com/math10/Ionic)?

**Comment by oozcitak** [comment]
I'm sorry but I can't debug your app. I barely have time to maintain this repo. I'll try to help if you can isolate your issue and post the steps to reproduce the error above.

**Comment by math10** [comment]
@oozcitak just start an ionic2 app an add plugin xml2js er try to use it you will get the error.
N.B: I saw that XMLNode has some error
![image](https://cloud.githubusercontent.com/assets/5284534/19436863/6ad871ee-9494-11e6-91b8-8f7f3d854012.png)
