### ISSUE TITLE
One Single source JS file to be used in browsers

### ISSUE THREAD

**Issue by gandhirajan** [oozcitak/xmlbuilder-js#142]
Hi, Is it possible to get single JS file with the complete source that do not require nodejs depedency to be used in the browser by including it in HTML? Is it possible by any chance?

**Comment by oozcitak** [comment]
You can use [browserify](http://browserify.org/) to concat the library into a single file. After installing `xmlbuilder` and `browserify` run the following inside the `xmlbuilder` directory:
``` bash
browserify -s xmlbuilder --bare ./lib/index.js -o xmlbuilder.js
```

**Comment by gandhirajan** [comment]
Thanks for the response. Works like charm.
