### ISSUE TITLE
commentBefore not available on root node

### ISSUE THREAD

**Issue by btsimonh** [oozcitak/xmlbuilder-js#144]
hi, am i correct in thinking that commentBefore and commentAfter can't be used on the root node?
is there a way to produce something like:

<?xml version="1.0"?>

<root>
  <node>mytext</node>
</root>

**Comment by btsimonh** [comment]
ok, worked it out.  here for anyone googling:
use begin, e.g.:
var doc = xmlbuilder.begin();
doc.dec({version: '1.0', encoding: 'UTF-8'});
doc.com("my comment text");
var el = doc.ele("myrootelement");

**Comment by oozcitak** [comment]
You could also use `create` with `commentBefore`:

```js
xmlbuilder.create('root')
  .commentBefore('my comment')
  .ele('node').txt('mytext');
```

**Comment by btsimonh** [comment]
hmm..  didn't try that exact thing, but sure i tried 

el = xmlbuilder.create('root');
el.commentBefore('my comment');

and it failed?

but begin is working fine for me :).
