### ISSUE TITLE
Wrong XML structure when generating from an array

### ISSUE THREAD

**Issue by andimeier** [oozcitak/xmlbuilder-js#151]
The mechanism to generate a XML structure from a (JSON) data structure containing arrays is broken:

Input structure:

```
var src = {
  "modules": [
    { "module": 1 },
    { "module": 2 }
  ]
}
```

then doing a:

    xmlbuilder.create(src).end()

Expected output would be:

```
<?xml version="1.0"?>
<modules>
  <module>1</module>
  <module>2</module>
</modules>
```

In different versions of xmlbuilder-js, it behaves differently:

xmlbuilder@3.1.0 ... OK:

```
<?xml version="1.0"?>
<modules>
  <module>1</module>
  <module>2</module>
</modules>
```

xmlbuilder@4.2.1 .. xmlbuilder@7.0.0 ... **NOT OK**

```
<?xml version="1.0"?>
<modules>
  <module>2</module>
</modules>
```

So, it swallows all but one array member.

xmlbuilder@8.2.2 (current version) ...  **NOT OK**

```
<?xml version="1.0"?>
<modules>
  <module>1</module>
</modules>
<modules>
  <module>2</module>
</modules>
```

Well, it is different, so apparently there was some change in this area, but this is no valid XML output (no root node).

So, at the moment, I am forced to use the outdated version xmlbuilder-js@3.1.0 because all newer versions fail at converting this structure correctly.

**Comment by oozcitak** [comment]
Did you check the `separateArrayItems` flag? It should give you the old behavior. https://github.com/oozcitak/xmlbuilder-js/wiki/Conversion-From-Object#arrays
