### ISSUE TITLE
\b in xml should be two valid characters but the lib throw error?

### ISSUE THREAD

**Issue by Duncan00** [oozcitak/xmlbuilder-js#153]
We are going to build following xml with "\b"
```
<?xml version="1.0" encoding="UTF-8"?>
<note>
    <to>A address with two characters \b</to>
</note>
```

https://github.com/oozcitak/xmlbuilder-js/blob/ab5987b12bc06e4da8c37cd7fec8f93085d96d28/src/XMLStringifier.coffee#L92
will throw error `"Invalid character (#{chr}) in string: #{str} at index #{chr.index}"`

Is it intended or I have some misunderstanding with xml?

**Comment by oozcitak** [comment]
Can you post your code please?

**Comment by Duncan00** [comment]
We are using `xml2js` package which uses `xmlbuilder`.

```
'use strict';

const xml2js = require('xml2js');
let xml_options = {
	headless: true,
	renderOpts: {
		pretty: false,
		indent: ' ',
		newline: ''
	}
};
let builder = new xml2js.Builder(xml_options);

let json = {
	note: {
		to: 'A address with two characters \b'
	}
};
let xml_result = builder.buildObject(json); // error from here
```

Thanks

**Comment by oozcitak** [comment]
Is that `\b` as a backspace character (U+0008) or a backslash followed by the letter `b`?

**Comment by Duncan00** [comment]
yep~ it's backslash followed by the letter b. 
`\b` character should be escaped in `js` or `json` even through it is not needed to escape in `xml`.
Thanks~
