### ISSUE TITLE
Pairwise elements from object

### ISSUE THREAD

**Issue by vlindhol** [oozcitak/xmlbuilder-js#155]
This is more of a question than an issue: is it possible to build pairwise elements from an object? What I mean is this:

```xml
<container>
  <foo>value1</foo>
  <bar>A</bar>
  <foo>value2</foo>
  <bar>B</bar>
  ...
</container>
```

I.e. there are always pairs of `foo` and `bar` elements, and the ordering is important. The container may also contain other tags than foo and bar. (Not a good schema, I know.)

**Comment by oozcitak** [comment]
This is not possible with an object literal. JS objects cannot have duplicate keys.
