### ISSUE TITLE
Feature request: Suppress empty elements

### ISSUE THREAD

**Issue by edtguy** [oozcitak/xmlbuilder-js#158]
Would it be possible to have a parameter to suppress the generation of elements that have a null text value?
I have a routine that retrieves a cell value from a named column and row number from a spreadsheet. If the retrieved value is null, I would like to suppress generation of the corresponding element. For example, if I have something like root.ele('Personal').ele({'first_name':cv('first_name',row),'middle_name':cv('middle_name',row),'last_name':cv('last_name',row'});
and middle_name is null, I want
<root>
    <Personal>
        <first_name>John</first_name>
        <last_name>Adams</last_name>
    </Personal>
</root>

I want to supress <middle_name/>

Currently, I have to test each element marked as optional in the corresponding .xsd file

var Personal = root.ele('Personal');
Personal.ele({'first_name':cv('first_name',row)});
if(cv('middle_name',row)) {
    Personal.ele({'middle_name':cv('middle_name',row)});
}
Personal.ele({'last_name':cv('last_name',row'});

An ignore null element would be most helpful, if possible.

Cheers,
Ed

**Comment by xeno** [comment]
Seconded. Not having this is causing me massive rewrites.

**Comment by oozcitak** [comment]
It appears I never released this feature on NPM. Sorry for that. This is now added in `v10.1.0`.

https://github.com/oozcitak/xmlbuilder-js/compare/v10.0.0...v10.1.0
