### ISSUE TITLE
multiple elements with different values

### ISSUE THREAD

**Issue by localguru** [oozcitak/xmlbuilder-js#159]
Hi,

for a shibb IdP I'd like to generate something like this:

```
      <mdui:UIInfo>
        <mdui:DisplayName xml:lang="de">Mein Titel</mdui:DisplayName>
        <mdui:DisplayName xml:lang="en">My title</mdui:DisplayName>
        <mdui:Description xml:lang="de">Ein Test</mdui:Description>
        <mdui:Description xml:lang="en">a test</mdui:Description>
      </mdui:UIInfo>
```

My js code:

```
                                  'mdui:UIInfo': {
                                    'mdui:DisplayName': { '@xml:lang': 'de', '#text': 'Mein Titel' },
                                    'mdui:DisplayName': { '@xml:lang': 'en', '#text': 'My title' },
                                    'mdui:Description': { '@xml:lang': 'de', '#text': 'Ein Test' },
                                    'mdui:Description': { '@xml:lang': 'en', '#text': 'A test' },
                                  }
```

This code ends up in just one element of DisplayName and Description

```
      <mdui:UIInfo>
        <mdui:DisplayName xml:lang="en">My title</mdui:DisplayName>
        <mdui:Description xml:lang="en">a test</mdui:Description>
      </mdui:UIInfo>
```

Any ideas?

Ciao!

**Comment by oozcitak** [comment]
See here please:

https://github.com/oozcitak/xmlbuilder-js/issues/71#issuecomment-71822225

**Comment by localguru** [comment]
Hi,

could you give an code example please?

I tried this, but it's not working:

```
                                  'mdui:UIInfo': {
                                    'mdui:DisplayName': [ 
                                      { '@xml:lang': 'de', '@text': 'A' },
                                      { '@xml:lang': 'en', '@text': 'B' }
                                    ],
                                    "mdui:DisplayName": [
                                      {
                                        "@xml:lang": "de",
                                        "#text": "AAA"
                                      },
                                      {
                                        "@xml:lang": "en",
                                        "#text": "AAA"
                                      }
                                    ],
```

Thanks

**Comment by localguru** [comment]
Am Donnerstag, den 25.05.2017, 13:05 -0700 schrieb Ozgur Ozcitak:
> See here please:
> 
> #71 (comment)

Sorry, but still don't get it. You you give an example please.

Thanks
marcus

**Comment by oozcitak** [comment]
Here is a workaround:
``` js
var obj = { 'mdui:UIInfo' : 
  [
    { 'mdui:DisplayName': { "@xml:lang": "de", "#text": "Mein Titel" } },
    { 'mdui:DisplayName': { "@xml:lang": "en", "#text": "My title" } },
    { 'mdui:Description': { "@xml:lang": "de", "#text": "Ein Test" } },
    { 'mdui:Description': { "@xml:lang": "en", "#text": "a test" } }
  ]
};

xmlbuilder.create(obj, {separateArrayItems: true});
```

**Comment by localguru** [comment]
Ozgur! Thank you, that's working :1st_place_medal:

**Comment by oozcitak** [comment]
Your code should also work too:

```js
'mdui:UIInfo': {
	"mdui:DisplayName": [
	  {
		"@xml:lang": "de",
		"#text": "AAA"
	  },
	  {
		"@xml:lang": "en",
		"#text": "BBB"
	  }
	],
```
I'll take a look.

**Comment by localguru** [comment]
Hi Ozgur,

how I do something like this? My problem is, that ContactPerson and EmailAddress are nested.

```
   <md:ContactPerson contactType="technical">
      <md:EmailAddress>mailto:example.technical.contact@garr.it</md:EmailAddress>
   </md:ContactPerson>
```

Thanks
Marcus

**Comment by rgilling** [comment]
I'm trying to generate a moderately complicated XML, but I've hit an issue similar to this one. The solution works at the first level, but on the second level it doesn't output correctly.  Here is a sample JSON object that I'm converting. The attribute groups are expanded correctly, but the nested attribute are not. I tried using both forms with each array element prefixed with 'attribute' and not. I'm trying to build a list of 'attribute' elements directly under each 'attribute-group'

{
      "category": {
        "@category-id": "twe-root",
        "display-name": {
          "#text": "Root",
          "@xml:lang": "x-default"
        },
        "description": {
          "#text": "Master Catalogue for Treasury Wines",
          "@xml:lang": "x-default"
        },
        "online-flag": {
          "#text": true
        },
        "attribute-groups": [
          {
            "attribute-group": {
              "@group-id": "wine",
              "display-name": {
                "#text": "Wine Attributes",
                "@xml:lang": "x-default"
              },
              "attribute": [
                {
                  "@attribute-id": "wineContentChannels",
                  "@system": false
                },
                {
                  "@attribute-id": "wineTastingNotesPDF",
                  "@system": false
                },
                {
                  "@attribute-id": "wineCOGS",
                  "@system": false
                },
                {
                  "@attribute-id": "wineCollection",
                  "@system": false
                },
                {
                  "@attribute-id": "wineType",
                  "@system": false
                },
                {
                  "@attribute-id": "wineVariety",
                  "@system": false
                },
                {
                  "@attribute-id": "wineBottleType",
                  "@system": false
                },
                {
                  "@attribute-id": "wineVintage",
                  "@system": false
                }
              ]
            }
          },
          {
            "attribute-group": {
              "@group-id": "coreProduct",
              "display-name": {
                "#text": "Core Product Attributes",
                "@xml:lang": "x-default"
              },
              "attribute": [
                {
                  "@attribute-id": "csrOnly",
                  "@system": false
                }
              ]
            }
          }
        ]
      }
    },

**Comment by oozcitak** [comment]
Testing with the current master branch at d8d24471670e885a94bfe91d4898bdf81ad127ea, it appears both issues are solved.

@localguru wtih this JS object:
```js
{
  'mdui:UIInfo': {
    "mdui:DisplayName": [
      { "@xml:lang": "de", "#text": "AAA" }
      { "@xml:lang": "en", "#text": "BBB" }
    ]
  }
}
```
the output is
```xml
<mdui:UIInfo>
  <mdui:DisplayName xml:lang="de">AAA</mdui:DisplayName>
  <mdui:DisplayName xml:lang="en">BBB</mdui:DisplayName>
</mdui:UIInfo>
```
@rgilling with your JS object above the output is:
```xml
<category category-id="twe-root">
  <display-name xml:lang="x-default">Root</display-name>
  <description xml:lang="x-default">Master Catalogue for Treasury Wines</description>
  <online-flag>true</online-flag>
  <attribute-groups>
    <attribute-group group-id="wine">
      <display-name xml:lang="x-default">Wine Attributes</display-name>
      <attribute attribute-id="wineContentChannels" system="false"/>
      <attribute attribute-id="wineTastingNotesPDF" system="false"/>
      <attribute attribute-id="wineCOGS" system="false"/>
      <attribute attribute-id="wineCollection" system="false"/>
      <attribute attribute-id="wineType" system="false"/>
      <attribute attribute-id="wineVariety" system="false"/>
      <attribute attribute-id="wineBottleType" system="false"/>
      <attribute attribute-id="wineVintage" system="false"/>
    </attribute-group>
  </attribute-groups>
  <attribute-groups>
    <attribute-group group-id="coreProduct">
      <display-name xml:lang="x-default">Core Product Attributes</display-name>
      <attribute attribute-id="csrOnly" system="false"/>
    </attribute-group>
  </attribute-groups>
</category>
```
Can you please check if those are the expected results?

**Comment by littlebacklash** [comment]
@oozcitak I know this issue is closed, but a new scenario came up. How could I generate an xml with this structure?

          <text>
            <paragraph>Symbolic text number 1</paragraph>
            <table>
              <thead>
                <tr>
                  <th>Desc</th>
                  <th>Value</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td>desc 1</td>
                  <td>value 1</td>
                </tr>
              </tbody>
            </table>
            <paragraph>** Symbolic text number 2 **</paragraph>
          </text>
          
where there are 2 paragraphs nodes, but in differents parts of the xml body.
Thanks in advance!!

**Comment by oozcitak** [comment]
@littlebacklash You can do something like this (note the `#text` decorator):

```js
const obj = {
  'text': {
    '#text': [
      { 'paragraph': 'Symbolic text number 1' }
      { 'table': '' }
      { 'paragraph': '** Symbolic text number 2 **' }
    ]
  }
}
```

**Comment by ZLU97** [comment]
@oozcitak I'm also running into issues regarding nested objects

I want an output looking like this:
```
...
  <Communication>
    <ChannelCode>Telephone<ChannelCode>
    <DialNumber>SomeDialNumber</DialNumber>
  </Communication>
  <Communication>
    <ChannelCode>Email<ChannelCode>
    <URI>SomeEmail</DialNumber>
  </Communication>
  <Communication>
    <ChannelCode>Fax<ChannelCode>
    <DialNumber>SomeFax</DialNumber>
  </Communication>
...
```

My JSON currently looks like this 
```
...
"Communication": [
                  [{"ChannelCode": {"#text": "Telephone"}}, {"DialNumber": {"#text": "SomeDialNumber"}}],
                  [{"ChannelCode": {"#text": "Email"}}, {"URI": {"#text": "SomeEmail"}}],
                  [{"ChannelCode": {"#text": "Fax"}}, {"DialNumber": {"#text": "SomeFax"}}]
                ]
...
```

But outputs this:
```
...
<Communication>
  <ChannelCode>Telephone</ChannelCode>
</Communication>
<Communication>
  <DialNumber>SomeDialNumber</DialNumber>
</Communication>
<Communication>
  <ChannelCode>Email</ChannelCode>
</Communication>
<Communication>
  <URI>SomeEmail</URI>
</Communication>
<Communication>
  <ChannelCode>Fax</ChannelCode>
</Communication>
<Communication>
  <DialNumber>SomeFax</DialNumber>
...
```

I've tried with the "#list" decorator as well, but didnt get my expected output either.
Any idea why ?
Thanks in advance
