### ISSUE TITLE
begin is not a function

### ISSUE THREAD

**Issue by maartenvandewaarsenburg** [oozcitak/xmlbuilder-js#164]
I would like to create the attached XML file.
[example.ofx.txt](https://github.com/oozcitak/xmlbuilder-js/files/1190743/example.ofx.txt)

If I understand well, I need to use the begin function in stead of the create function to be able to create the XML document from scratch to be able to insert a processing instruction before the root element.

However, when I use the begin function I get an error 

> TypeError: builder.begin is not a function

**Comment by oozcitak** [comment]
Can you post your code please?

**Comment by maartenvandewaarsenburg** [comment]
Certainly. It is the code from an example.

`#! /usr/bin/env node
'use strict';

const builder = require('xmlbuilder');

var root = builder.begin().ele('root', { 'rootAttribute': 'value' });`

**Comment by oozcitak** [comment]
What version of xmlbuilder are you using? begin() was added with [v8.0.0](https://github.com/oozcitak/xmlbuilder-js/blob/master/CHANGELOG.md#800---2016-03-25).

**Comment by maartenvandewaarsenburg** [comment]
Oh dear, 4.2.1. Reinstalled just now using npm (also tried yarn; makes no difference). Still 4.2.1.

Deleted entire node_modules directory and installed again. Now I have version 9.0.1.

Don't know how that came about.

No complaints anymore about existence of begin(). Sorry to have bothered you.
