### ISSUE TITLE
Add custom xmldec attributes

### ISSUE THREAD

**Issue by pablozandona** [oozcitak/xmlbuilder-js#166]
I'm not seeing any way to add a custom attributes to <?xml> node, like: 

`<?xml version="1.0" encoding="UTF-8" foo="bar"?>`

In documentation there are 3 predefined attributes: 'version', 'encoding' and 'standalone'.

**Comment by oozcitak** [comment]
That would be invalid XML. Only version, encoding and standalone are allowed in the declaration. See: https://www.w3.org/TR/xml11/#sec-prolog-dtd
