### ISSUE TITLE
Comment adding extra space

### ISSUE THREAD

**Issue by arulselvan** [oozcitak/xmlbuilder-js#168]
**com** method adding extra leading and trailing space.

var root = builder.create('squares');
root.com('f(x) = x^2');

I am not sure weather this is issue but my requirement need to mach some other xml file generated from other system.   

How to trim leading and trailing space on comment?

**Comment by arulselvan** [comment]
Just found there is an additional space hard coded on Comment writing, fixed and tried with local java script.
https://github.com/oozcitak/xmlbuilder-js/blob/master/src/XMLStringWriter.coffee
Line 58

**Comment by oozcitak** [comment]
I am afraid this is not currently possible.
