### ISSUE TITLE
Prolog not displaying

### ISSUE THREAD

**Issue by HeavenlyHost** [oozcitak/xmlbuilder-js#172]
Unable to get the prolog to display

<?xml version="1.0" encoding="utf-8"?>

This will not display... A code snippet

var writeToXML = function () {
    // Recreate the manifest file based on contents of the app directory

    var xml = builder.create('Elements', { version: '1.0', encoding: 'UTF-8' });
    xml.att({ 'xmlns': "http://schemas.microsoft.com/sharepoint/" });
    var module = xml.ele('Module', { 'Name': 'app' });

    fileList.forEach(function (file) {
        var modified = file.substring(2); // Removes first two characters as we don't need them
        var inverse = modified.split("/").join("\\");
        module.ele('File', { 'Path': inverse, 'Url': modified, 'ReplaceContent': "TRUE" });
    });

    xml.end({ pretty: true });

    console.log(xml);

    fs.writeFile("./app/test.xml", xml, function (err) {
        if (err) {
            return console.log(err);
        }
        console.log("The file was saved!");
    });
};

**Comment by oozcitak** [comment]
You shouldn't directly use the xml object, but use the return value of `end` which is the xml object converted to a string. e.g.:

```js
var xmlStr = xml.end({ pretty: true });

console.log(xmlStr);

fs.writeFile("./app/test.xml", xmlStr, function (err) {
    if (err) {
        return console.log(err);
    }
    console.log("The file was saved!");
});
```

**Comment by HeavenlyHost** [comment]
Fabulous that worked for me, KUDOS !

**Comment by HeavenlyHost** [comment]
Might be worth noting this on the readme :+1:
