### ISSUE TITLE
Using .begin with chunks does not handle root.ele(object)

### ISSUE THREAD

**Issue by mwillbanks** [oozcitak/xmlbuilder-js#173]
When passing objects to `root.ele({...})` and using `xmlbuilder.begin` the chunk passed to the onData ends up being a string: `<[object Object]>` rather than being parsed out and pushed.

**Comment by cmcowan** [comment]
same issue for me

**Comment by chrille112** [comment]
I'm facing the same issue. @mwillbanks @cmcowan , did you find a workaround?

**Comment by GaikwadPratik** [comment]
Till the issue is resolved, we can use below alternative:

`
class DataAttributes {
  constructor(metadata) {
    this['@constAttribute'] = 'value';
    for (let key in metadata) {
      this[`@${key}`] = `${metadata[key]}`;
    }
  }
}
`
