### ISSUE TITLE
element get auto closed when followed by loop

### ISSUE THREAD

**Issue by bivekrath** [oozcitak/xmlbuilder-js#174]
this the code being used:
```js
var builder = require('xmlbuilder');
i = 1;
var root = builder.create('squares')
if(i == 1){
root.ele('br')
for(var i = 1; i <= 2; i++)
{
  var item = root.ele('data');
  item.att('x', i);
  item.att('y', i * i);
}}
console.log(root.end({pretty: true}));
```
```xml
<?xml version="1.0"?>
<squares>
  <br/>
  <data x="1" y="1"/>
  <data x="2" y="4"/>
</squares>
```
in the above output br closes immediately. It should carry the entire data block.

**Comment by oozcitak** [comment]
How do you mean?

**Comment by oozcitak** [comment]
Try this:

```js
var builder = require('xmlbuilder');
i = 1;
var root = builder.create('squares')
if(i == 1){
var brNode = root.ele('br');
for(var i = 1; i <= 2; i++)
{
  var item = brNode.ele('data');
  item.att('x', i);
  item.att('y', i * i);
}}
console.log(root.end({pretty: true}));
```

**Comment by arunsraga** [comment]
**I have example as follows:**

var builder = require('xmlbuilder');
var obj = {  root: { xmlbuilder: {  test: {  test1: [ {
                                test11: {
                                        "@type": "type1"
                                },
                                test12: {
                                        "@type": "type1"
                                },
                                test13: {
                                        "@type": "type1"
                                }
                        } ]
                }
            }
  }
};

var xml = builder.create(obj).end({ pretty: true});
console.log(xml);

**Result is as follows:**
      <?xml version="1.0"?><root>
         <xmlbuilder>
            <test>
                <test1>
                   <test11 type="type1"/>
                   <test12 type="type1"/>
                  <test13 type="type1"/>
                </test1>
             </test>
        </xmlbuilder>
</root>

in above result test11, test12, test13 getting auto closed. how we can avoid auto closing.

**Comment by oozcitak** [comment]
You can use the `allowEmpty` writer option when calling end. See: https://github.com/oozcitak/xmlbuilder-js/wiki#converting-to-string

**Comment by arunsraga** [comment]
Thank You @oozcitak It worked.
