### ISSUE TITLE
How to change/remove XML header?

### ISSUE THREAD

**Issue by ashishnetworks** [oozcitak/xmlbuilder-js#178]
I have following piece of code

```
var xml = builder.create('root')
    .ele('parent')
    .ele('content')
    .dat('something').up()
    .up()
    .end()
console.log(xml) 
```

 which produces following output 

```
<?xml version="1.0"?>
<root>
<parent>
<content><![CDATA[something]]></content>
</parent><
</root>
```

Here I wanna remove the first line of the output which is called header that is `<?xml version="1.0"?>` and replace it from another line like `<vast version="2.5">` but I'm confused how shall I do that. Can somebody please tell me with an example how to do so?
FYI I have already read  a [similar thread](https://github.com/oozcitak/xmlbuilder-js/issues/160) from closed issues but there too I could not get any example

**Comment by oozcitak** [comment]
You can replace the declaration with:
https://github.com/oozcitak/xmlbuilder-js/wiki/XML-Prolog#xml-declaration
However the new declaration will be validated against the spec; you just can't insert arbitrary strings into the declaration.

**Comment by emaildano** [comment]
@oozcitak Would it be possible to output the following with one of those examples?

```
  <RoutingRules>
    <RoutingRule>
    <Condition>
      <KeyPrefixEquals>docs/</KeyPrefixEquals>
    </Condition>
    <Redirect>
      <ReplaceKeyPrefixWith>documents/</ReplaceKeyPrefixWith>
    </Redirect>
    </RoutingRule>
  </RoutingRules>
```

I'm trying to parse JSON into a format suitable for Amazon S3 Redirection Rules. I just need the header RoutingRules instead of `XML` or `!DOCTYPE`.

**Comment by oozcitak** [comment]
RoutingRules is not a header, it is the root element. You need to supress the XML Declaration. See the `headless` option in https://github.com/oozcitak/xmlbuilder-js/wiki#create.

**Comment by mrded** [comment]
Alternatively, you can use [begin()](https://github.com/oozcitak/xmlbuilder-js/wiki#begin) rather than [create()](https://github.com/oozcitak/xmlbuilder-js/wiki#create), like so:

```
var xml = builder.begin()
    .ele('root')
    .ele('parent')
    .ele('content')
    .dat('something').up()
    .up()
    .end()
console.log(xml) 
```

It will create an XML without a header.

**Comment by Pyxeel** [comment]
Try this too:

```js
const doc = builder.create(objectToParse);
return doc.end({ prettyPrint: true, headless: true });
```

**Comment by juancarlosgras** [comment]
Use `headless` config parameter:
```js
let root = xmlbuilder.create("root", {
      headless: true,
    });
```

**Comment by brajbaj** [comment]
> Try this too:
> 
> ```js
> const doc = builder.create(objectToParse);
> return doc.end({ prettyPrint: true, headless: true });
> ```

it works for xmlbuilder2
