### ISSUE TITLE
Breaking Changes from 9.0.7 to 10.0.0?

### ISSUE THREAD

**Issue by ctaepper** [oozcitak/xmlbuilder-js#179]
I can't see any breaking changes between those versions in the changelogs or git commits.
Would you please enlighten me?

**Comment by oozcitak** [comment]
Exception messages are [changed](https://github.com/oozcitak/xmlbuilder-js/commit/f066a3151d269e738ea37d87e5bf2470ef948b24) to provide better debug info. For example: `Missing CDATA text` became `Missing CDATA text. parent: <root>`. This has the potential to break code depending on the content of error messages, though the chances of someone writing such code is low (e.g. `catch(error) { if(error == "...") doSomething(); }`). I am adding the same explanation to the changelog now.

**Comment by ctaepper** [comment]
thanks for fast response!
