### ISSUE TITLE
Is `skipNullValues` working?

### ISSUE THREAD

**Issue by superliuwr** [oozcitak/xmlbuilder-js#180]
With it enabled I am still getting something like '<CityName/>' which is supposed to be discarded.

**Comment by bcomnes** [comment]
I'm getting empty tags when keys are set to null values.  Seems like this isn't working totally.

**Comment by bcomnes** [comment]
All references to this options seem to simply be comments.  Is it even implemented?

**Comment by oozcitak** [comment]
The flag is actually named `skipNullNodes`. Sorry for the typo; fixed in e7c4a61896cb8007020da4af89ed0b02e4d9fd15 and added to the wiki.
