### ISSUE TITLE
pretty option not working on browser 

### ISSUE THREAD

**Issue by anshulsachan** [oozcitak/xmlbuilder-js#182]
pretty option is not working on browser . It is displaying entire xml as single line. 

Code snippet 
const peopleNode = builder.create('roster').ele('people');
for (let i = 1; i <= 3; i++) {
        const person = builder.create('person').att('id', i);
        peopleNode.importDocument(person);
      }
const xml = peopleNode.end({
        pretty: true,
        indent: '  ',
        newline: '\n',
        allowEmpty: false,
        spacebeforeslash: '',
      });

It displays  correctly in console as mentioned in wiki and examples but on browser it is displayed like this. 

`<?xml version="1.0"?>
<roster>
  <people>
    <person id="1"/>
    <person id="2"/>
    <person id="3"/>
  </people>
</roster>`

Please help with this issue. Do we need to specify any property for browser?

**Comment by anshulsachan** [comment]
got it working after adding formatted xml on <pre> tag

**Comment by iongion** [comment]
@anshulsachan I got this in current version, what do you mean adding formatted xml on pre tag ? what pre tag ?

**Comment by anshulsachan** [comment]
i meant this 
<pre> adding the xml output here </pre>
