### ISSUE TITLE
Insert node Object in other node Object

### ISSUE THREAD

**Issue by gustavomanolo** [oozcitak/xmlbuilder-js#185]
I have a root element named "concepts" and i need to add a "concept" but i can't add it with **".ele() function"**

```
let nodeConcepts = xmlBuilder.begin().ele("concepts");
let nodeConcept = xmlBuilder.begin().ele("concept", {
      Quantity: 1,
      Price: 10
    });

nodeConcepts.ele(nodeConcept);
```

But i get the following error:
RangeError: Maximum call stack size exceeded

I'm trying to do like this, because the node "**nodeConcept**" can have multiple childs depending on some conditions, and then i add it to the global **nodeConcepts** to have a final XML tree.

Do you know how to do it? Thanks a lot.

**Comment by oozcitak** [comment]
Please see: https://github.com/oozcitak/xmlbuilder-js/wiki#importing-documents
