### ISSUE TITLE
> does not get replaced to &gt; in ele body

### ISSUE THREAD

**Issue by Matt-Bessette** [oozcitak/xmlbuilder-js#188]
If HTML is put in ele's body it becomes like:

`<p>` becomes `&lt;p>` instead of `&lt;p&gt;`

**Comment by oozcitak** [comment]
Are you sure about that? `>` in element text is correctly escaped to `&gt;`. If you are talking about attribute values, `>` is a valid character in attributes. Please see: https://www.w3.org/TR/xml/#d0e888
