### ISSUE TITLE
Create XML with ordered elements?

### ISSUE THREAD

**Issue by spaiz** [oozcitak/xmlbuilder-js#191]
I need to create an XML with elements in specific order. Is there any way to achieve this using object to xml processing? May be by using some special structure?

``` js
// not reliable
const test = {
  root: {
    child1: 'val1',
    child2: 'val2',
  }
};
```
I can't rely on the order of keys in the object cause:

> 4.3.3 Object
An object is a member of the type Object. It is an unordered collection of properties each of which contains a primitive value, object, or function. A function stored in a property of an object is called a 

If not, can I be sure the elements will preserve its order when building XML using a regular API?

``` js
const test = builder.create('root', { encoding: 'utf-8' })
  .ele('child1', 'val1').up()
  .ele('child2', 'val2').up();
```

Tnx :)

**Comment by oozcitak** [comment]
> can I be sure the elements will preserve its order when building XML using a regular API?

Yes nodes are crated immediately when `ele` is called, so the order is preserved.

>  Is there any way to achieve this using object to xml processing?

Not currently, but I can add a feature to order object keys by alphabetic order or with a user supplied compare function.

**Comment by spaiz** [comment]
We are validating the XML with XSD where the elements defined to be in particular order, so the alphabetical order will not help.

Anyway, if I can rely on the builder API as you told, it should solve our problem.

Thanks!
