### ISSUE TITLE
use of writer modification in .end()

### ISSUE THREAD

**Issue by btsimonh** [oozcitak/xmlbuilder-js#193]
hi all,
I wanted to 'unpretty' below a certain node type in the tree.  the solution i've ended up with, which works ok, is:
```
    var writer_temp = tt.options.writer;
    write_proto = Object.getPrototypeOf(writer_temp);
    // modify prototype to make it believe that everything below p contains text
    var org_el = write_proto.element;
    var new_el = function(node, level) {
        var out = '';
        var textadded = false;
        var newline = this.newline;
        if ((node.name === 'p') && this.dontprettytextnodes){
            console1.log('p');
            this.textispresent++;
            if (this.textispresent === 1){
                var space = this.space(level);
                out += space;
            }
            textadded = true;
        }
        out += org_el.call(this, node, level);
        if (textadded){
            if (this.textispresent === 1){
                out += newline;
            }
            this.textispresent--;
            if (!this.textispresent) {
              this.newline = this.newlinedefault;
              this.pretty = this.prettydefault;
            }
        }
        return out;
    };
    
    write_proto.element = new_el;
    msg.payload = Buffer.from(tt.end({ 
        pretty: true, 
        dontprettytextnodes: true,
    }), 'utf8');
    write_proto.element = org_el;
```

can this be done with writer function modification? something like this: 
```
tt.end({ 
        pretty: true, 
        dontprettytextnodes: true,
        writer: { element: somefn },
    })
```

what would 'somefn' look like?
I could not get my head around how to access 'this' inside the original writer and call the original code..

br,
s

p.s. basically, with plain 'dontprettytextnodes, you end up with:
```
        <p style="S1">
                <span style="S1">1</span>
        </p>
```
and I wanted (based on experience with parsers of this data):
```
        <p style="S1"><span style="S1">1</span></p>
```
any other ideas on how this may be best achieved welcome :)

**Comment by oozcitak** [comment]
Hello,

I made quite a few changes with 1c8ced424fd8b8fc89fea7525e9c984adea19bf1 to help customize writer behavior:

- When a writer function is overridden the original function is still accessable by prepending an underscore before its name. e.g. `_element`
- Signatures of all functions are changed to `func(node, options, level)` where `node` is the current node the writer is operating on, `options` are the settings passed while calling `end()` and `level` is the current level of the XML tree.
- The writer state can be accessed with the new property `options.state` where possible values are `{   None: 0,  OpenTag: 1,  InsideTag: 2,  CloseTag: 3 }`
- Added the new writer functions `space` and `endline` to help customize white space in the output
- Also added the `options.writer` property which is a reference to the writer itself, in case you can't use `this` inside the custom functions.

With those changes in place, your customization can be achieved by providing custom `space` and `endline` functions as follows:

``` js
newSpace = function(node, options, level) {
  // do not insert space before the opening tag of a p node's child
  // or the closing tag of a p node
  if (node.parent.name === "p" && options.State === 1)
    || (node.name === "p" && options.State === 3)) {
    return '';
  } else {
    return this._space(node, options, level);
  }
};

newEndline = function(node, options, level) {
  // do not insert newline after the closing tag of a p node's child
  // or the opening tag of a p node
  if (node.parent.name === "p" && options.State === 3)
    || (node.name === "p" && options.State === 1)) {
    return '';
  } else {
    return this._endline(node, options, level);
  }
};
```
Those functions are supplied to `end()` by creating a new writer:
``` js
builder.create('html')
  .ele('p', { 'style': 'S1' })
    .ele('span', { 'style': 'S1' })
      .txt(1)
  .end(builder.stringWriter({
    writer: { space: newSpace, endline: newEndline },
    pretty: true
  }));
```
I believe those changes will help in creating much cleaner custom writers with fewer code. Please let me know what you think.

**Comment by oozcitak** [comment]
`openNode` and `closeNode`  were actually internal functions. However, I liked your idea and now they work as you expected. I also added `options.user` which default to `{}` . Thanks for the suggestions. 👍 

Also, since `options` are passed recursively to all writer functions, you can simply set and unset `options.pretty` as shown below; you don't need to override `indent` and `endline` in this particular case.

```js
newOpenNode = function(node, options, level) {
  if (node.name === "p") {
    options.user.oldPretty = options.pretty;
    options.pretty = false;
  }
};

newCloseNode = function(node, options, level) {
  if (node.name === "p") {
    options.pretty = options.user.oldPretty;
  }
};
```
This outputs:
```xml
<p><span><span>sometext</span><span>sometext2</span></span></p>
```

**Comment by btsimonh** [comment]
when's the next npm release scheduled?
this now is awesome for my (specialist) application :).

**Comment by oozcitak** [comment]
This release will be a breaking change. I am taking the opportunity to add some major changes I had in mind. I'll probably release in a few days. 😸
