### ISSUE TITLE
Are attributes really nodes and should therefore invoke openNode() and closeNode() callbacks?

### ISSUE THREAD

**Issue by Simran-B** [oozcitak/xmlbuilder-js#196]
In [XMLWriterBase.coffee](https://github.com/oozcitak/xmlbuilder-js/blob/b38e655b1c8b3f940de5f764029d4cb6c4bc5d9e/src/XMLWriterBase.coffee#L95), openNode and closeNode are invoked:

```coffee
 attribute: (att, options, level) ->
    @openNode(att, options, level)
    r = ' ' + att.name + '="' + att.value + '"'
    @closeNode(att, options, level)
    return r
```

My understanding of the [XML Datamodel](https://www.w3.org/XML/Datamodel.html) is that the following things are **nodes**:

- elements (optionally with attributes)
- document (virtual root node)
- processing instructions
- comments
- data (text nodes?)

So elements yes, but **attributes are not nodes by themselves** it seems. There seems to be some information on the internet speaking about _attributes nodes_, but I couldn't even find the term _node_ in the XML specs.

If attributes are part of element nodes, then there should be no callbacks to openNode() and closeNode() in case of attributes. It's kinda handy to have callbacks, but maybe there should be different callbacks for attributes? This would make things easier IMO, because for attributes the function signature is different:

```js
    // for attributes, args[2] is undefined, signature seems to be (node, level)
    // for elements etc., the signature is (node, options, level) instead
            openNode: function(...args) {
                if (args[2] === undefined) {
                    const [node, level] = args
                    const indent = "  "
                    console.log(`${ indent.repeat(level) }openNode() - no options`)
                } else {
                    [node, options, level] = args
                    console.log(`${ options.indent.repeat(level) }openNode()`)
                }
                return this._openNode(...args)
            },
```

Or is this unintentional? Should the function signature be always (node, options, level)?

**Comment by oozcitak** [comment]
Yes, the function signature should always be `(node, options, level)`. I will fix that shortly. 

Separate `open` and `close` functions for attributes is a good idea too, it could allow more granularity to writers, and would be more technically correct. 

On that note, maybe adding a `nodeType` to the `options` object would also be handy, to distinguish between different node types.

**Comment by Simran-B** [comment]
Thanks for the addition of openAttribute() and closeAttribute() as well as the signature fix!

Regarding the nodeType property: for generic handlers like openNode() and closeNode() it's a must-have, or is there another way to find out the type of node? For specialized writer callbacks like `comment: function(node, option, level) { ... }` it's not needed, because it is only called for comment node, so you know what it is.

I wonder if nodeType should be numeric (integer), similar to the state property. Or would you use string names? What are the canonical names? As in, should it be `ele`, `element`, `Element`, `Element` or even something with `tag`?

**Comment by oozcitak** [comment]
Just added node types with d8de14769590b262e56b467df05db50855a0ad24. `type` is now a property of `node` objects with the following values:

```js
{
  Document : 1,
  Declaration : 2,
  DocType : 3,
  Element : 4,
  Raw : 5,
  Text : 6,
  CData : 7,
  Comment : 8,
  ProcessingInstruction : 9,
  AttributeDeclaration : 10,
  ElementDeclaration : 11,
  EntityDeclaration : 12,
  NotationDeclaration : 13,
  Dummy : 14 // internal
}
```
`NodeType` and `WriterState` are also exported by the module and can be used e.g.:
```js
const builder = require('xmlbuilder');

const nodeType = builder.nodeType;
const writerState = builder.writerState;
```
