### ISSUE TITLE
attributes with no value

### ISSUE THREAD

**Issue by danbars** [oozcitak/xmlbuilder-js#198]
Some times it is useful to have attributes with no value at all.
Examples are from html - `<button disabled />`
It is true that in many cases it would be equivalent to `<button disabled="true" />` but in some cases having the value breaks the code. For example, in vuejs you can write:
`<template v-slot:default></template>` but you cannot write `<template v-slot:default="true"></template>`
Currently if I set an attribute with no value it is not printed in the xml at all.
Is there a way to make it print those as no-value attributes?

If not, will you consider supporting it or get a PR? 
Thanks

**Comment by oozcitak** [comment]
Boolean attributes like `<button disabled />` are not valid XML, therefore they are not (and will not be) supported. Their equivalents `<button disabled="disabled" />` and `<button disabled="" />` are both supported.

If you really need boolean attributes of the first form, you can use the [`raw` function](https://github.com/oozcitak/xmlbuilder-js/wiki#raw-text-nodes) to insert arbitrary strings into the tree:
```js
.raw('<input type="button" disabled>')
```

**Comment by danbars** [comment]
Thanks. I also found in the code the undocumented `keepNullAttributes` option that results with `<template v-slot:default=""></template>` which seem to work for me.
Maybe it would be worth to add that option to documentation if anyone needs it.

**Comment by oozcitak** [comment]
Done. Added a [new wiki page](https://github.com/oozcitak/xmlbuilder-js/wiki/Builder-Options) for builder options.
