### ISSUE TITLE
Support for typescript definitions

### ISSUE THREAD

**Issue by GaikwadPratik** [oozcitak/xmlbuilder-js#200]
Why don't you add typescript definitions in the package? I mean there is one created https://www.npmjs.com/package/@types/xmlbuilder by @Wallymathieu. But those are not updated for quiet a long time. It would be easier to maintain them in the project.

**Comment by oozcitak** [comment]
Will do. Thanks. 🥂

**Comment by GaikwadPratik** [comment]
If you are okay, without any objections from @wallymathieu, I can import existing ones for quick resolution in a PR. I am sort of blocked because of them. As is I have created a PR https://github.com/DefinitelyTyped/DefinitelyTyped/pull/34084 for 782540c. Would be easier for any new consumer to get going.

**Comment by wallymathieu** [comment]
Are there named parameters in typescript nowadays?

**Comment by oozcitak** [comment]
@GaikwadPratik a PR from existing definitions would be much appreciated if @wallymathieu agrees. I can then just package the types with the library.

**Comment by wallymathieu** [comment]
I think it makes more sense to have the types in the package. If you could look at the PR to tell me if it's ok? I'm away from computers for a few days so won't be able to verify the PR.

**Comment by oozcitak** [comment]
`XMLCreateOptions` looks good in the PR. 

We need to add an `options` argument to `XMLWriter` because of b6c2503daa774b02579fb8c98c31877ea24861a1:

```ts
interface XMLWriter {
    [x: string]: ((e: XMLElementOrXMLNode, options: WriterOptions, level?: number) => void);
}
```
where `WriterOptions` is:
```ts
interface WriterOptions {
    pretty?: boolean;
    indent?: string;
    newline?: string;
    offset?: number;
    allowEmpty?: boolean;
    dontPrettyTextNodes?: boolean;
    spaceBeforeSlash?: string | boolean;
    user? :any;
    state?: WriterState;
}
```
and `WriterState` is:
```ts
enum WriterState {
    None = 0,
    OpenTag = 1,
    InsideTag = 2,
    CloseTag = 3
}
```
If you're in a hurry you can just add `options` as `any`.

This should make the types mostly compatible with the current release, I can add the rest of the changes on top of this PR.

**Comment by GaikwadPratik** [comment]
@oozcitak I have added the `WriteOptions` as indicated above in the https://github.com/oozcitak/xmlbuilder-js/pull/201. Please have a look.

**Comment by oozcitak** [comment]
Perfect thank you.
