### ISSUE TITLE
outdated typings

### ISSUE THREAD

**Issue by natergj** [oozcitak/xmlbuilder-js#204]
Thanks for the great library!
It looks like the typings file added in the 11.0.1 release is a bit out of date. It is missing typings for `xmlbuilder.streamWriter` and `xmlbuilder.stringWriter` functions exported from index.coffee and the options for some types seem to be out of date as well. This causes build failures in typescript projects that try to use those features.

**Comment by oozcitak** [comment]
Fixed by a4b9f796076cc6dba7de2a2e5a6f28b22d809f60.
