### ISSUE TITLE
Breaking changes from 11 to 12 ?

### ISSUE THREAD

**Issue by iongion** [oozcitak/xmlbuilder-js#205]
Are there any breaking changes ?
Did not find any mention of the 12.x release in the CHANGELOG

**Comment by JoniSykes** [comment]
+1 xml2js requiring latest xmlbuilder introducing breaking change

**Comment by JoniSykes** [comment]
@iongion looks like support for older versions of Node has been removed.

**Comment by oozcitak** [comment]
Thanks for the heads up. Just added to the release notes. Minimum node version is now 6.0.
