### ISSUE TITLE
Issue with method "attribute" in XMLNode lib

### ISSUE THREAD

**Issue by dexter1023** [oozcitak/xmlbuilder-js#210]
Hi,
I've got that error while create xml document from object: 
`TypeError: this.attribute is not a function
    at XMLDocument.element (/node_modules/xmlbuilder/lib/XMLNode.js:131:32)`
I checked code and there's no implementation of function "attribute".

**Comment by oozcitak** [comment]
Can you post your code please?

**Comment by afarah1** [comment]
For anyone wondering, this happens when you try to add an attribute to the document instead of a node. Example:

```
builder.create({
  root: {
    child: 'value'
  },
  '@attr': 'value'
});
```

Instead of

```
builder.create({
  root: {
    child: 'value',
    '@attr': 'value', // root attr, not child's
  },
});
```
