### ISSUE TITLE
Something recently started going wrong with the order of xml output

### ISSUE THREAD

**Issue by Savage-Moon** [oozcitak/xmlbuilder-js#215]
So a very small problem Im not sure if this is me using it wrong the whole time. but in the past the `<?qbxml version="2.0"?>` previously would print before the `<QBXML>` element. 

just today im noticing the switch. the code does it in run kit as well as my program 

![xmlbuilder](https://user-images.githubusercontent.com/16945057/58195641-73211f80-7c96-11e9-8cac-a786a262f767.PNG)

**Comment by oozcitak** [comment]
Try the `instructionBefore` function please.

**Comment by Savage-Moon** [comment]
That fixed it. Sorry it was just out of nowhere. Thanks  so much for the quick help.
