### ISSUE TITLE
Support for multi line comment   

### ISSUE THREAD

**Issue by arunsraga** [oozcitak/xmlbuilder-js#219]
I want to comment multi line i.e 
```js
var obj = {
   'target' : [  { 'group': {
                        '@name': "myGroup", "@id" : "123"}},
                 { 'group': {
                        '@name': "myGroup2", "@id" : "456"}
                     }  ]
}

var resultObj = {  "#comment": obj }
var xml = builder.create(resultObj ).end({ pretty: true});
console.log(xml);
```
I'm getting following Error.
**"node_modules\xmlbuilder\lib\XMLComment.js:15
        throw new Error("Missing comment text");**

I was Expecting Result  as follows: 
```xml
<!-- <target>
        <group name="myGroup" id="123" />
        <group name="myGroup2 " id ="456" />
 </target> --> 
```

**Comment by oozcitak** [comment]
Comment text needs to be a string. e.g. `{  "#comment": "some text here" }`. So, in order to have an XML tree inside a comment, you need to convert it into a string first: `var resultObj = {  "#comment": obj.end() }`.

**Comment by arunsraga** [comment]
@oozcitak Thank You. It works fine.
