### ISSUE TITLE
 The generated xml has not been exported

### ISSUE THREAD

**Issue by laumega1** [oozcitak/xmlbuilder-js#221]
Once I generate my xml code, the most I get is to take it out on the screen through the console but what I want is to be able to have a physical file with this code. How can it be done? 
I print it with this command line: console.log (doc.toString ({pretty: false}));

**Comment by OctavioMaia** [comment]
This should help you out https://flaviocopes.com/node-writing-files/

Just replace the content with your generated XML

**Comment by laumega1** [comment]
> Esto debería ayudarlo a salir https://flaviocopes.com/node-writing-files/
> 
> Simplemente reemplaza el contenido con tu XML generado


Thank you very much for the response, it has been helpful
