### ISSUE TITLE
Can't remove attribute heired from root

### ISSUE THREAD

**Issue by OctavioMaia** [oozcitak/xmlbuilder-js#222]
I'm building a SAML Request using xmlbuilder and it has helped me a lot so far.
Sadly there's a bug I can't seem to fix no matter what I try.

This is the function I created to generate the XML, [(link)](https://pastebin.com/r277hUiw) and this the resulting XML [(link)](https://pastebin.com/zHvKzNNg).

On the "Extensions" tag I don't have any attributes, but it's heiring the "xmlns":"urn:oasis:names:tc:SAML:2.0:protocol" from the root.
Can anyone help me fix this? I can't have that attribute there

**Comment by oozcitak** [comment]
I added a test case, but I can't see an `xmlns` attribute on the `Extensions` element. Can you please confirm that the sample code you sent is the actual code you use?

**Comment by OctavioMaia** [comment]
This is the whole file https://pastebin.com/raw/wpCGS2ZS

I'm calling stripExtension() to remove the xmlns attribute from the Extensions element.

**Comment by OctavioMaia** [comment]
> I added a test case, but I can't see an `xmlns` attribute on the `Extensions` element. Can you please confirm that the sample code you sent is the actual code you use?

**Comment by oozcitak** [comment]
It appears to be inserted by `xml-crypto`.

**Comment by OctavioMaia** [comment]
> It appears to be inserted by `xml-crypto`.

Thank you, I'll have to manually remove it then.

**Comment by oozcitak** [comment]
NP. You can raise the issue to `xml-crypto` or maybe [xmldom](https://github.com/jindw/xmldom). since this is the package used by `xml-crypto` to parse and serialize the XMLdocument.
