### ISSUE TITLE
Typescript Typings Error on Cannot find module 'stream'.

### ISSUE THREAD

**Issue by serkon** [oozcitak/xmlbuilder-js#223]
ERROR in projects/logo/excel/node_modules/xmlbuilder/typings/index.d.ts(1,22): error TS2307: Cannot find module 'stream'.

This error is exists at 13.0.2 version, when i downgrade to 12.0.1 version there are no warning while compiling.

Thanks for interest

**Comment by oozcitak** [comment]
Can you please add `"node"` to `types` in your `tsconfig.json`?

**Comment by VILLAN3LL3** [comment]
Adding `"types": ["node"]` tp tsconfig.base.json (Angular 10) doesn't work for me. Any ideas?

**Comment by oozcitak** [comment]
@VILLAN3LL3 Can you make a test so I can reproduce?

**Comment by VILLAN3LL3** [comment]
Thanks for you quick reply @oozcitak 
I fixed it while trying to create a sample project for you: I had to add `"types": ["node"]` to tsconfig.app.json instead of tsconfig.base.json. :-)

**Comment by vazenfino** [comment]
Try removing unnecessary import statements.

**Comment by axj2047** [comment]
import {EventEmitter } from '@angular/core';
