### ISSUE TITLE
separateArrayItems doesn't seem to work

### ISSUE THREAD

**Issue by pconnell99** [oozcitak/xmlbuilder-js#229]
I'm trying to create an array like:-

```
'pnp:ContentTypeBindings': [{
     'pnp:ContentTypeBinding': { "@ContentTypeID": "0x0101", "@Default": "true" }
        },
        {
            'pnp:ContentTypeBinding': { "@ContentTypeID": "0x0120" }
        }]
```

Expecting:-
```
<pnp:ContentTypeBindings>
            <pnp:ContentTypeBinding ContentTypeID="0x0101" Default="true" />
            <pnp:ContentTypeBinding ContentTypeID="0x0120" />
          </pnp:ContentTypeBindings>
```

But getting:-

```
 <pnp:ContentTypeBindings>
            <pnp:ContentTypeBinding ContentTypeID="0x0101" Default="true"/>
 </pnp:ContentTypeBindings>
  <pnp:ContentTypeBindings>
            <pnp:ContentTypeBinding ContentTypeID="0x0120"/>
 </pnp:ContentTypeBindings>
```

separateArrayItems is set to default false, so I was hoping this would aggregate them.  These elements are being built as objects and then passed into an ele() call off the previous parent object.

Thoughts?  Am I doing this wrong?

**Comment by pconnell99** [comment]
I have to build up the object dynamically as I go, so using chaining will not work -  am I losing context by not chaining the calls?  I'm creating objects off the back of the previous object.

**Comment by oozcitak** [comment]
Try with separateArrayİtems set to true please.

**Comment by pconnell99** [comment]
Worked (had not previously oddly enough).  Thanks, closing.
