### ISSUE TITLE
 m³ ，     throw  Error,

### ISSUE THREAD

**Issue by bailingliu** [oozcitak/xmlbuilder-js#230]
https://github.com/oozcitak/xmlbuilder-js/blob/master/src/XMLStringifier.coffee
line:145~147

the string   流量m³/秒,  why   throw  Error,  m³   is a common string。

**Comment by oozcitak** [comment]
Unfortunately `³` is not allowed in XML names. Please see: https://www.w3.org/TR/xml/#NT-Names
