### ISSUE TITLE
Option to force all nodes to use CDATA

### ISSUE THREAD

**Issue by danpetitt** [oozcitak/xmlbuilder-js#232]
It would be great to have an option to either ensure all nodes output as CDATA and do not xml escape, or when using the JSON notational method of building the XML you could declare the node text as `#CDATA` instead of `#TEXT` to get a more customisable individual ability to do this.

**Comment by danpetitt** [comment]
Ignore me on that; after looking at your code, I have just found that you already have this, but its undocumented in the wiki: `#cdata-section`

**Comment by oozcitak** [comment]
It is in the wiki here: https://github.com/oozcitak/xmlbuilder-js/wiki#cdata-nodes and here: https://github.com/oozcitak/xmlbuilder-js/wiki/Conversion-From-Object#cdata-decorator

**Comment by danpetitt** [comment]
I am very sorry; I just couldnt find it for looking; i was searching the wrong things :-)

**Comment by oozcitak** [comment]
No problem. Happy to help.
