### ISSUE TITLE
Maximum call stack size exceeded while create XML

### ISSUE THREAD

**Issue by raja2raj02** [oozcitak/xmlbuilder-js#235]
i tried to create a xml from a json data. i am getting an error "Maximum call stack size exceeded" from console. usually get this error because of any methods called itself until the stack exceeded.is this known issue or any work around?

![error](https://user-images.githubusercontent.com/22573352/76061478-9f015d80-5fa9-11ea-84f1-e7a83bafc109.png)

**Comment by oozcitak** [comment]
Any chance you can share the JSON so that I can reproduce?

**Comment by raja2raj02** [comment]
Here i am attaching the json file.
[JsonData.txt](https://github.com/oozcitak/xmlbuilder-js/files/4302983/JsonData.txt)

**Comment by raja2raj02** [comment]
the issue was circular json. After resolving that i am getting the below error 
"ERROR Error: Invalid character in name"
![error1](https://user-images.githubusercontent.com/22573352/76159762-a65f6d00-6149-11ea-81c8-68069e15b932.png)

**Comment by oozcitak** [comment]
You have some invalid names in your JSON. For example on line 241:
```js
"jsonRule": {
    "$ref": "$"
},
```
The `"$"` character cannot be used in XML names, so you need to correct those.
