### ISSUE TITLE
Trouble creating element

### ISSUE THREAD

**Issue by Mithrilhall** [oozcitak/xmlbuilder-js#236]
How would one create an element like

`<video:video></video:video>`

When I try

`myXML.ele('video:video');`

I get the following error:

> This page contains the following errors:
error on line 1 at column 329: Namespace prefix video on video is not defined
Below is a rendering of the page up to the first error.

**Comment by oozcitak** [comment]
I don't think this is related to xmlbuilder. Can you post more of your code?

**Comment by Mithrilhall** [comment]
You were correct. I apologize. It was an issue elsewhere in my code.
