### ISSUE TITLE
XML to JSON

### ISSUE THREAD

**Issue by ashishgehlot** [oozcitak/xmlbuilder-js#237]
Hi guys, 
Its really wonderful library to  build XML. 
I have requirement to generate  JSON from XML again. 
Is their any function ?

**Comment by oozcitak** [comment]
Yes. See the [convert](https://oozcitak.github.io/xmlbuilder2/builder-functions.html#convert) function and [serialization settings](https://oozcitak.github.io/xmlbuilder2/serialization.html#serialization-settings) for details:

```js
const { convert } = require('xmlbuilder2');

const jsonObj = '{ "root": "node": { } }';
const XML = convert(jsonObj, { format: 'xml' });
console.log(obj);
```
```xml
<?xml version="1.0"?><root><node/></root>
```

**Comment by ashishgehlot** [comment]
Thanks @oozcitak  Its really helpful.
