### ISSUE TITLE
Don't want <?xml version  in toString()

### ISSUE THREAD

**Issue by clintberry** [oozcitak/xmlbuilder-js#27]
Is there a way to leave out the xml version tag at the beginning of xml doc?

e.g. I don't want this to display at the top of my xml:

<?xml version="1.0"?>

**Comment by Pyxeel** [comment]
> Headless documents are now officially supported, e.g.:
> 
> ```js
> xmlbuilder.create('root', { headless: true })
> ```

If that don't work, try this:

```js
const doc = builder.create(objectToParse);
return doc.end({ prettyPrint: true, headless: true });
```
