### ISSUE TITLE
nested lodash path nightmare in windows!

### ISSUE THREAD

**Issue by zxdong262** [oozcitak/xmlbuilder-js#53]
the loadash structure is nested, make the path name tooooooo long!
it take me five hour to solve this ( it works in win7 ,but do not work in xp ,really hard to find out)
please try use one lodash or something.

**Comment by jdalton** [comment]
Just a heads up. [lodash v3](https://github.com/lodash/lodash/releases/tag/3.0.0) has significantly reduced the dep graphs of its modularized packages:
```
lodash.assign@3.0.0
├─┬ lodash._baseassign@3.0.1
│ ├── lodash._basecopy@3.0.0
│ └─┬ lodash.keys@3.0.3
│   ├── lodash.isarguments@3.0.0
│   ├── lodash.isarray@3.0.0
│   └── lodash.isnative@3.0.0
└─┬ lodash._createassigner@3.0.0
  ├── lodash._bindcallback@3.0.0
  └── lodash._isiterateecall@3.0.1
```

There's even a simplified form:
```
lodash._baseassign@3.0.1
├── lodash._basecopy@3.0.0
└─┬ lodash.keys@3.0.3
  ├── lodash.isarguments@3.0.0
  ├── lodash.isarray@3.0.0
  └── lodash.isnative@3.0.0
```

You can also cherry-pick modules from `lodash`, for example `require('lodash/array/chunk')`.

**Comment by oozcitak** [comment]
Thanks for the heads up @jdalton
