### ISSUE TITLE
Empty Elements vs. Self-Closing Tags With Blank Strings

### ISSUE THREAD

**Issue by droppedoncaprica** [oozcitak/xmlbuilder-js#65]
Hey, it looks like if you pass a blank string into an `.ele()` call, it doesn't create a self-closing tag correctly.

    xmlbuilder.create('someElem')
      .ele('selfClose', {}, '')
    .root().toString({pretty: true})

Will return as:

    <someElem>
      <selfClose></selfClose>
    </someElem>

Personally, I expected this to match the `null` or `undefined` behavior and have a self-closing tag here:

    xmlbuilder.create('someElem')
      .ele('selfClose', {}, undefined)
        .up()
      .ele('anotherSelfClose', {}, null)
    .root().toString({pretty: true})

Which will return:

    <someElem>
      <selfClose/>
      <anotherSelfClose/>
    </someElem>

It's not a huge deal, but it was an issue I'd ran into when accessing a particularly stringent SOAP API.  Is this the correct behavoir?  

If you don't have time to handle this, could you point me in the right direction in the code?  Originally I was going to submit a PR but I wasn't sure about the entry point for this is, and it is very early in the morning.

**Comment by droppedoncaprica** [comment]
Thanks @oozcitak!

**Comment by MarvelousDE** [comment]
What do I need to do, if I explicitly want those tags for a legacy system?

**Comment by oozcitak** [comment]
See the `allowEmpty` option: https://github.com/oozcitak/xmlbuilder-js/wiki#converting-to-string

**Comment by OluyideO** [comment]
Please what can I do if I want to remove those empty tag
<someElem>
  <selfClose/>
  <anotherSelfClose/>
</someElem>
I will like to remove the self closing tags using the xmlbuilder.js
