### ISSUE TITLE
format problem in end with pretty true

### ISSUE THREAD

**Issue by coldkite** [oozcitak/xmlbuilder-js#68]
problem occurs in the file : XMLStringifier.coffee 
```coffee
  elEscape: (str) ->
    str.replace(/&/g, '&amp;')
       .replace(/</g, '&lt;')
       .replace(/>/g, '&gt;')
       .replace(/\r/g, '&#xD;')
```

Sometimes, we need to put CDATA in the same line with tags, so we might write code like this:

```javascript
some_element.ele('url', null,'\<![CDATA[' + 'http://www.github.com' + ']]\>');
```
while the origin multi-line is like this:
```javascript
var url = some_element.ele('url'));
url.dat('http://www.github.com')
```

if we 'replace(/</g, '&lt;')' and replace(/>/g, '&gt;'), it will cause problems.

Do you think it is necessary to take the one line requirement into account? 
Just like provide some parameters in pretty function?

**Comment by foolkite** [comment]
Yes, it is pretty good!!

**Comment by oozcitak** [comment]
I have finally implemented this. Details are in the change log of v6.0.0 and the wiki.

https://github.com/oozcitak/xmlbuilder-js/blob/master/CHANGELOG.md#600---2016-03-20
https://github.com/oozcitak/xmlbuilder-js/wiki#xml-writers

The usage is similar to my proposal above. For example:

```js
var xml = xmlbuilder.create('root').ele('url').dat('http://www.github.com');
var str = xml.end({
  writer: {
    cdata: function(node, level) {
      return '<![CDATA[' + node.text + ']]>'; // no newline in custom converter
    }
  }
});
```
