### ISSUE TITLE
Is there an xml un-builder?

### ISSUE THREAD

**Issue by protobi** [oozcitak/xmlbuilder-js#69]
Given an XML string, is there a tool that can generate a JS object (or JSON string) for which XML builder will generate an equivalent XML string?

In particular, tools that I can see online (e.g. http://www.utilities-online.info/xmltojson/#.VK4W82TF-pw)  don't handle the `#list` feature at all, and don't use the `@` symbol for tag attributes,
   `{"-attribute":value}` rather than  `{ "@attribute":value}`

**Comment by oozcitak** [comment]
There is xml2js: https://github.com/Leonidas-from-XIV/node-xml2js
