### ISSUE TITLE
Problem geting pretty to work

### ISSUE THREAD

**Issue by zahmet** [oozcitak/xmlbuilder-js#73]
Hello,

I want todo something like this:

var xml = builder.create('TestXML', { version: '1.0', encoding: 'UTF-8'});
xml.end({ pretty: true});

The endresult is "only" `</TestXML>`

 I was expecting it to be:
<?xml version="1.0" encoding="UTF-8">
</TestXML>

If I do run it like this:
var builder = require('xmlbuilder');
var xml = builder.create('root')
  .ele('xmlbuilder', {'for': 'node-js'})
    .ele('repo', {'type': 'git'}, 'git://github.com/oozcitak/xmlbuilder-js.git')
  .end({ pretty: true});

Then it "works" and I get the header I'm looking for, but I want to be able to manipulate the XML with for-loop and similar things, so I want to work with it like an object, I don't just want to put ele after ele.

What am I missing here?

**Comment by oozcitak** [comment]
The end result should be:

``` xml
<?xml version="1.0" encoding="UTF-8"?>
<TestXML/>
```

The header is not omitted unless you use the `headless` option. Can you recheck please?

**Comment by zahmet** [comment]
I just made a new node-js file as this:

var builder = require('xmlbuilder');
var fs = require('fs');

var xml = builder.create('TestXML', { version: '1.0', encoding: 'UTF-8'});
xml.end({ pretty: true});

var xmlfilename = require('path').resolve(__dirname, "test.xml");
fs.writeFile(xmlfilename, xml, function (err) {
  if (err) throw(err);
  console.log('write done');
});

and I get just get:

<TestXML/>

**Comment by oozcitak** [comment]
You should assign the return value of `end` to a variable and write it to the file.

**Comment by zahmet** [comment]
Thank you, I'm 99% sure that I used to have a variable to handle the return from end, but I guess I did something wrong with it and then removed that.

Worked fine now.

**Comment by oozcitak** [comment]
Cheers.

**Comment by bhupendra1011** [comment]
Hi All , it is possible to pretty print https://stackoverflow.com/questions/75557251/how-to-convert-json-object-to-xml-with-every-property-of-tag-in-new-line
