### ISSUE TITLE
engine field needlessly restrictive (re: io.js)

### ISSUE THREAD

**Issue by mzgol** [oozcitak/xmlbuilder-js#74]
The engine field contains the entry:
```js
"node": "0.8.x || 0.10.x || 0.11.x  || 1.0.x"
```
which means io.js 1.1.0 is not accepted. io.js follows semver so it doesn't make sense to allow 1.0.x and not allow any 1.x.x.

**Comment by bigmonkeyboy** [comment]
And indeed the new "stable" node  0.12.0 ....

**Comment by oozcitak** [comment]
Agreed. Can you send a PR with just `>= 0.8.x`?

**Comment by oozcitak** [comment]
That should be `>= 0.8.0`
