### ISSUE TITLE
Escape characters

### ISSUE THREAD

**Issue by zahmet** [oozcitak/xmlbuilder-js#76]
Hello, 

I think I'm just missing how to escape characters with this.
So I have lots of data and I want to make a XML out of it, now I want all the <, > to still work, but if there is a "value" that has <, > in them I want to escape that to &lt or &gt

How do I do this?

At first I was thinking just do some escapeXml on the string I get after .end()

But that would escape the normal tags also, then I thought I would just use it on the 
xml.ele("header", object)

but since the 2nd value here is a object, I can't use replace on that...

I'm guessing it's something simple since it looks like it's already doing this automatic its just that it doesn't seem to work with > 

So not sure if there is anything automatic that does'nt work with > 
or if I'm missing how to use it.

an example of a line and how it shows up after i've run my jscode:
`
<VLAN Name="Test" IPAddress="Test_IP" IP4Broadcast="Test_BR" VLANID="1" BaseInterface="fabric2" IfaceId="5" PrivateIP.0="&lt;inherit>" PrivateIP.1="&lt;inherit>"/>
`

Here at the end I have the 
`
PrivateIP.0="&lt;inherit>" PrivateIP.1="&lt;inherit>"
but it should be PrivateIP.0="&lt;inherit&gt" PrivateIP.1="&lt;inherit&gt"
`

**Comment by oozcitak** [comment]
I can't see your sample code. Can you please read the formatting guide and edit your comment.

https://guides.github.com/features/mastering-markdown/

**Comment by zahmet** [comment]
Alright sorry about that didn't notice that the code was missing.

But it's just a minor example the question is if there is any automatic escape in the xmlbuilder or if I need to escape them on my own, and if so, if there is any easy way todo it.

**Comment by oozcitak** [comment]
There is automatic escaping but `>` in attribute values is not escaped according to the spec: http://www.w3.org/TR/2000/WD-xml-c14n-20000119.html#charescaping

Only the following characters are escaped in attribute values:
```
&           &amp
<           &lt
"           &quot
\t          &#x9
\n          &#xA
\r          &#xD
```
If you need to escape `>` in attribute values you need to do it yourself.

**Comment by zahmet** [comment]
Alright, is there a reason why > isn't escaped?

Is there a easy way to escape this, since when I add elements I use objects and I can't just use replace on them.

'''javascript
xml = builder.create("header", { version: '1.0', encoding: 'UTF-8'});
xml.ele(data[i].value, data[i].cfg);
'''

Where data[i].cfg is a object with some data, now I want to escape that part but since it's an object I can't simply do some .replace with > since it's not a string.
Do you have any suggestion on how to do that?

**Comment by oozcitak** [comment]
Why do you want to escape `>`? It is not required by the spec.

**Comment by oozcitak** [comment]
If you really need to do that you can provide a custom converter function to `create`

``` js
var root = xmlbuilder.create('root', {
  stringify: {
    attValue: function(str) {
      return str.replace(/&/g, '&amp;')
                     .replace(/</g, '&lt;')
                     .replace(/>/g, '&gt;')
                     .replace(/"/g, '&quot;')
                     .replace(/\t/g, '&#x9;')
                     .replace(/\n/g, '&#xA;')
                     .replace(/\r/g, '&#xD;');
    }
  }
});
```

**Comment by zahmet** [comment]
Thanks, that's what I was looking for.
Well I simply need to escape > since it's needed for the XML I'm creating.

The custom converter worked wonders!
