### ISSUE TITLE
Set type of root node?

### ISSUE THREAD

**Issue by OKNoah** [oozcitak/xmlbuilder-js#78]
I'm trying to create an object like 

	<?xml version="1.0" encoding="UTF-8"?>
	<external_stories type="array">
		<external_story>

I tried 

	var xml = builder.create( "external_stories", { encoding: 'UTF-8', 'type': 'array' } )

**Comment by oozcitak** [comment]
Try calling `att` on the root object instead:

```js
var xml = builder.create( "external_stories", { encoding: 'UTF-8' } ).att('type', 'array');
```

**Comment by OKNoah** [comment]
Thank you!

**Comment by oozcitak** [comment]
You're welcome.
