### ISSUE TITLE
invalid xml generated in case of json array

### ISSUE THREAD

**Issue by smartIam** [oozcitak/xmlbuilder-js#79]
consider my json array is
"Characteristic": [
                          {
                            "Name": "Roaming Allow Outgoing ",
                            "Value": "False"
                          },
                          {
                            "Name": "Roaming Allow Incoming  ",
                            "Value": "False"
                          },
                          {
                            "Name": "Roaming Allow ",
                            "Value": "False"
                          }
                                      
                        ]"

xmlbuilder output is::
![untitled](https://cloud.githubusercontent.com/assets/12098017/7317411/28127b12-ea9e-11e4-8bfc-3fdd6e4b6ede.png)

expexted output is:
                                         
![untitled1](https://cloud.githubusercontent.com/assets/12098017/7317413/2d7a2bf4-ea9e-11e4-8c5f-ff91c3c18989.png)

**Comment by oozcitak** [comment]
Currently arrays are simply expanded, so to achieve the xml above your code should be like:
```json
[
   { "Characteristic":
      {
         "Name": "Roaming Allow Outgoing ",
         "Value": "False"
      }
   },
   { "Characteristic":
      {
         "Name": "Roaming Allow Incoming ",
         "Value": "False"
      }
   },
   { "Characteristic":
      {
         "Name": "Roaming Allow",
         "Value": "False"
      }
   }
]
```
