### ISSUE TITLE
how to change element value?

### ISSUE THREAD

**Issue by rapiddata** [oozcitak/xmlbuilder-js#83]
I created an xmlbuilder doc object.
Now I want to change an element value.
How do I do that?
Thanks
Leo

**Comment by rapiddata** [comment]
can say xmldoc.children[0]='hello world'  ?

**Comment by oozcitak** [comment]
You can delete the old node and create a new one:
``` js
var ele = root.ele('old text')
              .remove()
              .ele('new text'));
```
Or you can edit the value of the text node. But this is undocumented and may change in the future:
``` js
xmldoc.children[0].children[0].value='hello world';
```
