### ISSUE TITLE
How to dynamically add content to a doc?

### ISSUE THREAD

**Issue by peterkingsbury** [oozcitak/xmlbuilder-js#87]
Given the following desired structure:

```xml
<root>
  <someEle a="1" b="2" />
  <someContainer>
    <entry id="1"/>
    <entry id="2"/>
    <entry id="3"/>
    ...
    <entry id="n"/>
  </someContainer>
</root>
```

I am able to generate everything _except_ the dynamic contents of **someContainer**, using the following:

``` javascript
var xml = builder.create({
  root: {
    someEle: {
      '@a': 1,
      '@b': 2
    },
    someContainer: {
    }
  }
}).end({ pretty: true });
```

If I call .end() like so, the document appears as the XML specified above. However, if I omit the call to .end(), and instead append something like this...

``` javascript
// 'xml' should be the someContainer node
for (var i = 0; i < 10; i++) {
  xml.ele('entry', { id: i });
}
xml.doc().end({ pretty: true }); // OR
xml.root().doc().end({ pretty: true }); // OR
xml.end({ pretty: true });
```

... I am left with a document structure which appears to be a format internal to xmlbuilder-js that is used to build the final doc (it contains some elements from my code), but I am unsure how to generate the expected XML document.

What is it that I'm doing wrong? What is the correct procedure to mix mostly-static and dynamically-generated XML document content?

Thanks!

**Comment by oozcitak** [comment]
Here is one way of doing this:

```js
var builder, root, container, i, xmlString;
builder = require('xmlbuilder');

// Static part, keep a reference to the root element
// so that we can append the container later
root = builder.create('root');
root.ele('someEle', { a: '1', b: '2'});

// Create the container element under root
// Keep the reference to the container element
container = root.ele('someContainer');

// Add the entries under container
for (i = 0; i < 10; i++) {
  container.ele('entry', { id: i });
}

// Convert the entire xml document to string
xmlString = root.end({pretty: true});

console.log(xmlString);
```
And the result:
```xml
<?xml version="1.0"?>
<root>
  <someEle a="1" b="2"/>
  <someContainer>
    <entry id="0"/>
    <entry id="1"/>
    <entry id="2"/>
    <entry id="3"/>
    <entry id="4"/>
    <entry id="5"/>
    <entry id="6"/>
    <entry id="7"/>
    <entry id="8"/>
    <entry id="9"/>
  </someContainer>
</root>
```
There are other ways of achieving this. If you have mostly static content, you could build the static part with js objects, then traverse to the `container` element and add the dynamic content as above. See: https://github.com/oozcitak/xmlbuilder-js/wiki#traversing-the-document-tree

**Comment by peterkingsbury** [comment]
Thanks! That is exactly what I needed.
