### ISSUE TITLE
Creating by object doesn't include XML header

### ISSUE THREAD

**Issue by rdpascua** [oozcitak/xmlbuilder-js#90]
object:

    var obj = {
        auth: {
          type: { '#text': 'AuthReq' },
          value: { '#text': 'foo' }
        }
    };

using:

    xml.create(obj).toString();

    console.log("%s", xml.create(obj));

output:

    <auth><type>AuthReq</type></auth>

Am I doing something wrong?

EDIT: function call.

**Comment by oozcitak** [comment]
Try calling `end` instead of `toString`. `toString` converts the current node to string while `end` converts the entire document. See:

https://github.com/oozcitak/xmlbuilder-js/wiki#converting-to-string

**Comment by rdpascua** [comment]
Thanks @oozcitak, I was actually referring to this wiki https://github.com/oozcitak/xmlbuilder-js/wiki/Conversion-From-Object
