### ISSUE TITLE
Upgrading node engine 

### ISSUE THREAD

**Issue by yashprit** [oozcitak/xmlbuilder-js#92]
I got following warning 
`npm WARN engine xmlbuilder@2.2.1: wanted: {"node":"0.8.x || 0.10.x"} (current: {"node":"4.2.1","npm":"2.7.3"})` 

while installing some package which utilize xmlbuilder. Could we please upgrade engine because 0.8 is quite old nodejs in comparison to current 4.X.X

**Comment by oozcitak** [comment]
We already support the latest node.js. But it seems that the package depending on xmlbuilder uses an old build. Can you please inform the package author to upgrade xmlbuilder to the current 3.1.0 version.
