### ISSUE TITLE
Array with attributes not expanding as expected

### ISSUE THREAD

**Issue by pabdavis** [oozcitak/xmlbuilder-js#93]
Hi, I've got objects which have arrays which have different attributes which are not being expanded as expected: 

```js
{
    "Title" : {
        "@lang" : "eng",
        "#text" : "Show Title"
    },      
    "Cast" : [
        {       
            "@role" : "Host",
            "#text" : "Interview Person"
        },      
        {       
            "@role" : "Guest",
            "#text" : "Guest Person"
        }       
    ],      
    "Category" : [
        {       
            "@lang" : "eng",
            "@type" : "B23",
            "#text" : "Game Show"
        },      
        {       
            "@lang" : "eng",
            "@type" : "C34",
            "#text" : "Family"
        },  
        {       
            "@lang" : "eng",
            "@type" : "B23",
            "#text" : "Topical"
        }       
    ]       
}
```

Expected: 
```xml
<root>
  <Title lang="eng">Show Title</Title>
  <Cast role="Host">Interview Person</Cast>
  <Cast role="Guest">Guest Person</Cast>
  <Category lang="eng" type="B23">Game Show</Category>
  <Category lang="eng" type="C34">Family</Category>
 <Category lang="eng" type="B23">Topical</Category>
</root>
```

Got the following which only applies the last attributes to the tag (which are not correct for the 1st entry in cast and 2nd entry in category) : 
```xml
<root>
    <Title lang="eng">Show Title</Title>
    <Cast role="Guest">
      Interview Person
      Guest Person
    </Cast>
    <Category lang="eng" type="B23">
      Game Show
      Family
      Topical
    </Category>
  </root>
```

I've read thru issues 79 and 82 and got the following data structure to produce the desired xml output, but seems odd that elements are having to be mixed into the '#list'.   Wanted to provide this bug/use/test case in attempt to help. 

Is there another possible work-around other than below that you could suggest?

```js
{
    "Title" : {
        "@lang" : "eng",
        "#text" : "Show Title"
    },
    "#list" : [
        { "Cast":
            {
                "@role" : "Host",
                "#text" : "Interview Person"
            }
        },
        { "Cast":
            {
                "@role" : "Guest",
                "#text" : "Guest Person"
            }
        },
        {
          "Category":
            {
                "@lang" : "eng",
                "@type" : "B23",
                "#text" : "Topical"
            }
        }
    ]
} 
```

**Comment by oozcitak** [comment]
First I wrote a negative response to this and went on to include an example to prove my case. However, I really couldn't come up with a good example to justify the current behavior. I am inclined to change array handling so that `item: [1, 2, 3]` converts to `<item>1</item><item>2</item><item>3</item>` instead of `<item><1/><2/><3/></item>`. This will be a breaking change; so if anyone is against this, please chime in.

Referenced issues: https://github.com/oozcitak/xmlbuilder-js/issues/79, https://github.com/oozcitak/xmlbuilder-js/issues/82

**Comment by oozcitak** [comment]
This feature is now available in a [feature branch](https://github.com/oozcitak/xmlbuilder-js/compare/betterlisthandling).

**Comment by pabdavis** [comment]
Thanks for the quick response!

**Comment by oozcitak** [comment]
Published with version 4.0.0.

**Comment by DanielSmedegaardBuus** [comment]
Hi :)

A good example to keep the old behavior is that without it, it's impossible to decorate a list (is that the phrasing for adding attributes to a list container element?

In other words, it will be impossible to use xmlbuilder to generate XML documents to certain consumers that expect a certain format. I'm using code based on [saml2-js](https://github.com/Clever/saml2), and it breaks with xmlbuilder >=4.0.0.

Code like this:

```
  return xmlbuilder.create({
    'md:EntityDescriptor': {
      '@xmlns:md': XMLNS.MD,
      '@xmlns:ds': XMLNS.DS,
      '@entityID': entity_id,
      '@validUntil': (new Date(Date.now() + 1000 * 60 * 60 * 24 * 365 * 10)).toISOString(),
      'md:SPSSODescriptor': [
        {
          '@protocolSupportEnumeration': 'urn:oasis:names:tc:SAML:1.1:protocol urn:oasis:names:tc:SAML:2.0:protocol'
        }, {
          'md:KeyDescriptor': certificate_to_keyinfo('signing', signing_certificate)
        }, {
          'md:KeyDescriptor': certificate_to_keyinfo('encryption', encryption_certificate)
        }, {
          'md:SingleLogoutService': {
            '@Binding': 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect',
            '@Location': assert_endpoint
          },
          'md:AssertionConsumerService': {
            '@Binding': 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST',
            '@Location': assert_endpoint,
            '@index': '0'
          }
        }
      ]
    }
  }).end();
```

Used to be able to create a `<md:SPSSODescriptor protocolSupportEnumeration="urn:oasis:names:tc:SAML:1.1:protocol urn:oasis:names:tc:SAML:2.0:protocol">` decorated list element with other child elements. With this change, it creates one such element, closes it immediately, and then wraps each child element in an undecorated `<md:SPSSODescriptor>` node.

At least, AFAICS this is the reason... Am I being retarded, or is it still possible to create such a node decorated with attributes while still having arbitrary child nodes (non-wrapped in dupes of the list element)?

Cheers :)

**Comment by oozcitak** [comment]
Did you check the `separateArrayItems` flag? It should give you the old behavior. https://github.com/oozcitak/xmlbuilder-js/wiki/Conversion-From-Object#arrays
