### ISSUE TITLE
Escaping of special XML characters not working

### ISSUE THREAD

**Issue by dpalic** [oozcitak/xmlbuilder-js#95]
I have an issue with the escaping/encoding of strings in attributes

If I want to write this string into XML attribute

```
err.msg = Start tag seen without seeing a doctype first. Expected e.g. “<!DOCTYPE html>“.

  .att('message', err.msg);
```

xmlbuilder is making following xml-attribute

```
message="Start tag seen without seeing a doctype first. Expected e.g. “&lt;!DOCTYPE html>“."
```

Afaik, xmlbuilder should do a encoding of:
```
< into &lt;
> into &gt;
“ into &#8220; (only in non UTF-8)
" into &quot;   (not tested)
```

I am using for my personal cross check: 
ASCII http://coderstoolbox.net/string/#!encoding=xml&action=encode&charset=us_ascii
UTF-8 http://coderstoolbox.net/string/#!encoding=xml&action=encode&charset=utf_8

Am I using the xmlbuilder wrong, or is here an issue with the encoding/escaping of special chars?

**Comment by oozcitak** [comment]
xmlbuilder assumes that all strings are UTF8. If you are working with internationalized XML documents, you need to convert it yourself while serializing/deserializing the document. See for example: [iconv-lite](https://github.com/ashtuchkin/iconv-lite) and [node-iconv](https://github.com/bnoordhuis/node-iconv).

If you need a more complete solution with internationalization support, you may take a look at: [libxmljs](https://github.com/polotek/libxmljs). I haven't personally used it, but it appears to support internationalization.

`>` in attribute value is not escaped because it is not required by the [spec](http://www.w3.org/TR/2000/WD-xml-c14n-20000119.html#charescaping). But you can override this by providing a custom converter function to `create`:
``` js
var root = xmlbuilder.create('root', {
  stringify: {
    attValue: function(str) {
      return str.replace(/&/g, '&amp;')
                .replace(/</g, '&lt;')
                .replace(/>/g, '&gt;')
                .replace(/"/g, '&quot;');
    }
  }
});
```

**Comment by dpalic** [comment]
thank you for your very fast revert.

The spec says:
> All character information items are represented in a Canonical XML document by their UTF-8 encoding, with the following exceptions:

> In character data and attribute values, the character information items "<" and "&" are represented by "&lt;" and "&amp;" respectively.
> In character data, the character information item ">" is represented by "&gt;".
> In attribute values, the double-quote character information item (") is represented by "&quot;".
> In character data, the carriage-return (#xD) character information item is represented by "&#xD;".
> In attribute values, the character information items TAB (#x9), newline (#xA), and carriage-return (#xD) are represented by "&#x9;", "&#xA;", and "&#xD;" respectively.

So shouldn't it be also done properly by xmlbuilder lib?

**Comment by oozcitak** [comment]
It is considered good practice to escape `>` in attribute values, but it is not strictly required by the spec. For example this is a well-formed XML document:
```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<root>
  <condition check="age > 21"/>
  <condition check="age &gt; 21"/>
</root>
```
Checked with: https://validator.w3.org/check

**Comment by dpalic** [comment]
okay thank you. Have not know this...

Regarding your stringify example. Is it working for you? It fails on my side to create a instance of root

**Comment by oozcitak** [comment]
It does:
```js
var xmlbuilder = require('xmlbuilder');

var root = xmlbuilder.create('root', {
  stringify: {
    attValue: function(str) {
      return str.replace(/&/g, '&amp;')
                .replace(/</g, '&lt;')
                .replace(/>/g, '&gt;')
                .replace(/"/g, '&quot;');
    }
  }
});

root.att("message", "Start tag seen without seeing a doctype first. Expected e.g. “<!DOCTYPE html>“.");

console.info(root.end({pretty: true}));
```
Output:
```xml
<?xml version="1.0"?>
<root message="Start tag seen without seeing a doctype first. Expected e.g. “&lt;!DOCTYPE html&gt;“."/>
```
