### ISSUE TITLE
XMLStringifier does not handle HTML character entities

### ISSUE THREAD

**Issue by feedler** [oozcitak/xmlbuilder-js#97]
The stringifier replaces all occurences of `&` with `&amp;` but does not consider that the string might contain HTML character entities itself (like for example `&uuml;` or `&#252;` for the umlaut ü). The following change in the (javascript-) source code should fix this:

    // Current source:
    return str.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/\r/g, '&#xD;');
    // Fixed source:
    return str.replace(/(?!&(\D+|#\d+);)&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/\r/g, '&#xD;');

**Comment by feedler** [comment]
Had a mistake in the regex myself. This version should work now:

    return str.replace(/(?!&#?\S+;)&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/\r/g, '&#xD;');

**Comment by oozcitak** [comment]
Are you aiming to avoid double encoding of `&`? Also isn't `/(?!&\S+;)&/g` sufficient in your regex?

**Comment by feedler** [comment]
Yes - that's what I'm aiming at. And you're right: your regex should be sufficient. :)

**Comment by oozcitak** [comment]
I am going to add a `doubleEncode` flag for this. It will default to `true` so that current default behavior will remain unchanged. When explicitly set to `false` it will use your regex, Would that work for you?

**Comment by feedler** [comment]
Yes, that will work - thank you very much!

**Comment by oozcitak** [comment]
You can now create the builder with the `noDoubleEncoding` flag set to `false`
See: https://github.com/oozcitak/xmlbuilder-js/blob/master/test/issues/97.coffee#L9
